import { ReactNode } from 'react';
import { cn } from '@/lib/utils';

export function GrowthPage({ eyebrow, title, description, action, children }: { eyebrow?: string; title: string; description?: string; action?: ReactNode; children: ReactNode }) {
  return <div className="mx-auto max-w-[1440px] p-4 md:p-8 lg:p-10"><div className="mb-8 flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div>{eyebrow && <p className="growth-gradient-text mb-3 text-[10px] font-bold uppercase tracking-[.22em]">{eyebrow}</p>}<h1 className="font-growth-display text-3xl font-extrabold tracking-tight text-white md:text-4xl">{title}</h1>{description && <p className="mt-3 max-w-2xl text-sm leading-6 text-white/45">{description}</p>}</div>{action}</div>{children}</div>;
}
export function GrowthCard({ children, className }: { children: ReactNode; className?: string }) { return <div className={cn('growth-surface rounded-2xl p-5', className)}>{children}</div>; }
export function GrowthButton({ children, variant='primary', className, ...props }: React.ButtonHTMLAttributes<HTMLButtonElement> & { variant?: 'primary'|'secondary'|'danger' }) { return <button {...props} className={cn('inline-flex h-11 items-center justify-center gap-2 rounded-lg px-4 text-sm font-bold transition duration-200 disabled:cursor-not-allowed disabled:opacity-45', variant==='primary' && 'growth-brand-button text-white hover:-translate-y-0.5 hover:brightness-110', variant==='secondary' && 'border border-white/10 bg-white/5 text-white hover:border-white/20 hover:bg-white/10', variant==='danger' && 'border border-red-400/20 bg-red-500/10 text-red-200 hover:bg-red-500/20', className)}>{children}</button>; }
export const growthInputClass = 'h-11 w-full rounded-lg border border-white/10 bg-black/35 px-3 text-sm text-white outline-none transition placeholder:text-white/20 focus:border-[#8C0DC2]/70 focus:ring-2 focus:ring-[#8C0DC2]/15';
export const growthTextareaClass = 'min-h-28 w-full resize-y rounded-lg border border-white/10 bg-black/35 px-3 py-3 text-sm leading-6 text-white outline-none transition placeholder:text-white/20 focus:border-[#8C0DC2]/70 focus:ring-2 focus:ring-[#8C0DC2]/15';
export function GrowthField({ label, children, hint }: { label: string; children: ReactNode; hint?: string }) { return <label className="block"><span className="mb-2 block text-xs font-bold uppercase tracking-[.08em] text-white/45">{label}</span>{children}{hint && <span className="mt-1.5 block text-xs text-white/30">{hint}</span>}</label>; }
export function GrowthBadge({ children, tone='neutral' }: { children: ReactNode; tone?: 'lime'|'amber'|'red'|'neutral' }) { return <span className={cn('inline-flex rounded-full border px-2.5 py-1 text-[10px] font-bold uppercase tracking-[.1em]', tone==='lime'&&'border-emerald-400/20 bg-emerald-400/10 text-emerald-300', tone==='amber'&&'border-amber-300/20 bg-amber-300/10 text-amber-200', tone==='red'&&'border-red-300/20 bg-red-300/10 text-red-200', tone==='neutral'&&'border-white/10 bg-white/5 text-white/45')}>{children}</span>; }
export function EmptyGrowth({ title, description }: { title: string; description: string }) { return <GrowthCard className="py-16 text-center"><div className="growth-brand-button mx-auto mb-5 grid h-12 w-12 place-items-center rounded-xl text-xl text-white">↗</div><h2 className="font-growth-display text-lg font-bold text-white">{title}</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-white/40">{description}</p></GrowthCard>; }
