'use client';

import { ChangeEvent, useRef, useState } from 'react';
import Papa from 'papaparse';
import { AlertTriangle, Download, FileSpreadsheet, Upload, X } from 'lucide-react';
import { GrowthImportResult, mapGrowthImportRows } from '@/lib/growth-import';
import { GrowthButton, GrowthCard } from './growth-ui';

async function parseFile(file:File){const extension=file.name.split('.').pop()?.toLowerCase();if(extension==='xlsx'||extension==='xls'){const XLSX=await import('xlsx');const data=await file.arrayBuffer();const workbook=XLSX.read(data);return XLSX.utils.sheet_to_json<Record<string,unknown>>(workbook.Sheets[workbook.SheetNames[0]],{defval:''})}const text=await file.text();const parsed=Papa.parse<Record<string,unknown>>(text,{header:true,skipEmptyLines:true,transformHeader:(header)=>header.trim()});if(parsed.errors.length&&!parsed.data.length)throw new Error(parsed.errors[0].message);return parsed.data}

export default function GrowthImportDialog({hasExisting,onClose,onApply}:{hasExisting:boolean;onClose:()=>void;onApply:(result:GrowthImportResult)=>void}){
  const inputRef=useRef<HTMLInputElement>(null);const [result,setResult]=useState<GrowthImportResult|null>(null);const [fileName,setFileName]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  const select=async(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];if(!file)return;setBusy(true);setError('');try{const rows=await parseFile(file);const mapped=mapGrowthImportRows(rows);if(!mapped.sources.length&&!mapped.campaigns.length)throw new Error('Não encontrei colunas de Origem ou Campanha. Usa o modelo disponível.');setResult(mapped);setFileName(file.name)}catch(reason){setResult(null);setError(reason instanceof Error?reason.message:'Não foi possível ler o ficheiro.')}finally{setBusy(false)}};
  const downloadTemplate=()=>{const csv=Papa.unparse([{Origem:'Meta Ads',Campanha:'Campanha Leads',Objetivo:'Gerar contactos',Investimento:150000,Contactos:80,Qualificados:30,Reunioes:12,Propostas:6,Vendas:2,Receita:600000},{Origem:'Orgânico',Campanha:'',Objetivo:'',Investimento:0,Contactos:20,Qualificados:8,Reunioes:3,Propostas:2,Vendas:1,Receita:250000}],{delimiter:';'});const url=URL.createObjectURL(new Blob(['\uFEFF',csv],{type:'text/csv;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download='modelo-growth-room.csv';link.click();URL.revokeObjectURL(url)};
  return <div className="fixed inset-0 z-[100] grid place-items-center bg-black/80 p-4 backdrop-blur-sm"><div className="max-h-[92vh] w-full max-w-3xl overflow-y-auto rounded-3xl border border-white/10 bg-[#111111] p-6 shadow-2xl md:p-8"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#FF5D00]">Importação rápida</p><h2 className="mt-2 text-2xl font-bold text-white">Importar Excel ou CSV</h2><p className="mt-2 text-sm leading-6 text-white/45">Reconhecemos automaticamente origem, campanha, investimento e números do funil.</p></div><button type="button" onClick={onClose} className="rounded-xl p-2 text-white/35 hover:bg-white/5 hover:text-white"><X className="h-5 w-5"/></button></div>
    <div className="mt-7 grid gap-4 md:grid-cols-[1fr_auto]"><button type="button" onClick={()=>inputRef.current?.click()} className="flex min-h-36 items-center justify-center gap-4 rounded-2xl border border-dashed border-[#FF5D00]/30 bg-[#FF5D00]/[.04] px-5 text-left hover:bg-[#FF5D00]/[.08]"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-[#FF5D00]/10 text-[#FF5D00]"><Upload className="h-5 w-5"/></span><span><strong className="block text-sm text-white">{busy?'A ler o ficheiro…':fileName||'Escolher ficheiro'}</strong><small className="mt-1 block text-white/40">.xlsx, .xls ou .csv · máximo 500 linhas</small></span></button><button type="button" onClick={downloadTemplate} className="flex items-center justify-center gap-2 rounded-2xl border border-white/10 px-5 text-sm font-bold text-white/60 hover:bg-white/5 hover:text-white"><Download className="h-4 w-4"/>Baixar modelo</button><input ref={inputRef} className="hidden" type="file" accept=".xlsx,.xls,.csv,text/csv" onChange={select}/></div>
    {error&&<p className="mt-4 rounded-xl border border-red-400/15 bg-red-500/10 p-4 text-sm text-red-200">{error}</p>}
    {result&&<div className="mt-6"><div className="grid gap-3 sm:grid-cols-3"><GrowthCard><FileSpreadsheet className="h-4 w-4 text-[#FF5D00]"/><p className="mt-3 text-2xl font-black text-white">{result.sources.length}</p><p className="mt-1 text-xs text-white/35">origens encontradas</p></GrowthCard><GrowthCard><FileSpreadsheet className="h-4 w-4 text-[#FF5D00]"/><p className="mt-3 text-2xl font-black text-white">{result.campaigns.length}</p><p className="mt-1 text-xs text-white/35">campanhas encontradas</p></GrowthCard><GrowthCard><p className="text-xs text-white/35">Totais reconhecidos</p><p className="mt-3 text-sm font-bold text-white">{result.totals.contacts} contactos · {result.totals.sales} vendas</p><p className="mt-1 text-xs text-white/40">{new Intl.NumberFormat('pt-AO').format(result.totals.attributedRevenue)} Kz de receita</p></GrowthCard></div>{hasExisting&&<div className="mt-4 flex gap-3 rounded-xl border border-amber-300/15 bg-amber-300/[.06] p-4 text-xs leading-5 text-amber-100/65"><AlertTriangle className="mt-0.5 h-4 w-4 shrink-0"/>Ao confirmar, as origens e campanhas atuais serão substituídas pelos dados importados.</div>}<div className="mt-6 flex justify-end gap-3"><GrowthButton variant="secondary" onClick={onClose}>Cancelar</GrowthButton><GrowthButton onClick={()=>onApply(result)}>Aplicar dados importados</GrowthButton></div></div>}
  </div></div>;
}
