import { ReactNode } from 'react';
import { cn } from '@/lib/utils';

export function GrowthPage({ eyebrow, title, description, action, children }: { eyebrow?: string; title: string; description?: string; action?: ReactNode; children: ReactNode }) {
  return <div className="mx-auto max-w-[1440px] p-4 md:p-8 lg:p-10"><div className="mb-8 flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div>{eyebrow && <p className="mb-3 text-[10px] font-bold uppercase tracking-[.22em] text-[#d9ff6a]">{eyebrow}</p>}<h1 className="text-3xl font-extrabold tracking-tight text-white md:text-4xl">{title}</h1>{description && <p className="mt-3 max-w-2xl text-sm leading-6 text-white/45">{description}</p>}</div>{action}</div>{children}</div>;
}
export function GrowthCard({ children, className }: { children: ReactNode; className?: string }) { return <div className={cn('rounded-2xl border border-white/[.08] bg-white/[.045] p-5 shadow-[0_18px_60px_rgba(0,0,0,.12)]', className)}>{children}</div>; }
export function GrowthButton({ children, variant='primary', className, ...props }: React.ButtonHTMLAttributes<HTMLButtonElement> & { variant?: 'primary'|'secondary'|'danger' }) { return <button {...props} className={cn('inline-flex h-11 items-center justify-center gap-2 rounded-xl px-4 text-sm font-bold transition disabled:cursor-not-allowed disabled:opacity-45', variant==='primary' && 'bg-[#d9ff6a] text-[#0c110d] hover:bg-[#e4ff91]', variant==='secondary' && 'border border-white/10 bg-white/5 text-white hover:bg-white/10', variant==='danger' && 'border border-red-400/20 bg-red-500/10 text-red-200 hover:bg-red-500/20', className)}>{children}</button>; }
export const growthInputClass = 'h-11 w-full rounded-xl border border-white/10 bg-black/20 px-3 text-sm text-white outline-none placeholder:text-white/20 focus:border-[#d9ff6a]/50 focus:ring-2 focus:ring-[#d9ff6a]/10';
export const growthTextareaClass = 'min-h-28 w-full resize-y rounded-xl border border-white/10 bg-black/20 px-3 py-3 text-sm leading-6 text-white outline-none placeholder:text-white/20 focus:border-[#d9ff6a]/50 focus:ring-2 focus:ring-[#d9ff6a]/10';
export function GrowthField({ label, children, hint }: { label: string; children: ReactNode; hint?: string }) { return <label className="block"><span className="mb-2 block text-xs font-bold uppercase tracking-[.08em] text-white/45">{label}</span>{children}{hint && <span className="mt-1.5 block text-xs text-white/30">{hint}</span>}</label>; }
export function GrowthBadge({ children, tone='neutral' }: { children: ReactNode; tone?: 'lime'|'amber'|'red'|'neutral' }) { return <span className={cn('inline-flex rounded-full border px-2.5 py-1 text-[10px] font-bold uppercase tracking-[.1em]', tone==='lime'&&'border-[#d9ff6a]/20 bg-[#d9ff6a]/10 text-[#d9ff6a]', tone==='amber'&&'border-amber-300/20 bg-amber-300/10 text-amber-200', tone==='red'&&'border-red-300/20 bg-red-300/10 text-red-200', tone==='neutral'&&'border-white/10 bg-white/5 text-white/45')}>{children}</span>; }
export function EmptyGrowth({ title, description }: { title: string; description: string }) { return <GrowthCard className="py-16 text-center"><div className="mx-auto mb-5 grid h-12 w-12 place-items-center rounded-2xl bg-[#d9ff6a]/10 text-xl text-[#d9ff6a]">↗</div><h2 className="text-lg font-bold text-white">{title}</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-white/40">{description}</p></GrowthCard>; }
