'use client';

import Link from 'next/link';
import { FormEvent, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ArrowLeft, ArrowRight, CalendarPlus, Copy, Mail, ShieldCheck, UserMinus, X } from 'lucide-react';
import { EmptyGrowth, GrowthBadge, GrowthButton, GrowthCard, GrowthField, GrowthPage, growthInputClass } from '@/components/growth/growth-ui';
import { formatGrowthKz, GrowthPeriod, growthApi } from '@/lib/growth-api';

export default function GrowthClientPage() {
  const id=String(useParams().id); const router=useRouter(); const qc=useQueryClient(); const [modal,setModal]=useState<'period'|'invite'|null>(null);
  const query=useQuery({queryKey:['growth-client',id],queryFn:()=>growthApi.client(id)});
  const createPeriod=useMutation({mutationFn:(data:Record<string,unknown>)=>growthApi.createPeriod(id,data),onSuccess:(period)=>{qc.invalidateQueries({queryKey:['growth-client',id]});router.push(`/clientes/${id}/periodos/${period.id}`)}});
  const invite=useMutation({mutationFn:(data:{name:string;email:string})=>growthApi.invite(id,data),onSuccess:()=>{qc.invalidateQueries({queryKey:['growth-client',id]});setModal(null)}});
  const revoke=useMutation({mutationFn:growthApi.revoke,onSuccess:()=>qc.invalidateQueries({queryKey:['growth-client',id]})});
  if(query.isLoading)return <div className="p-10 text-white/40">A carregar cliente…</div>;
  if(!query.data)return <div className="p-10 text-white">Cliente não encontrado.</div>;
  const client=query.data;
  return <GrowthPage eyebrow="Growth Room do cliente" title={client.companyName} description={client.mainGoal||'Define o objetivo principal para orientar as leituras estratégicas.'} action={<Link href="/clientes" className="inline-flex items-center gap-2 text-sm text-white/45 hover:text-white"><ArrowLeft className="h-4 w-4"/>Todos os clientes</Link>}>
    <div className="mb-7 grid gap-4 lg:grid-cols-[1fr_.8fr]"><GrowthCard><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-white/30">Períodos de performance</p><p className="mt-2 text-sm text-white/45">Prepara, revê e publica cada leitura.</p></div><GrowthButton onClick={()=>setModal('period')}><CalendarPlus className="h-4 w-4"/>Novo período</GrowthButton></div></GrowthCard><GrowthCard><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-white/30">Acessos do cliente</p><p className="mt-2 text-sm text-white/45">{client.accesses?.filter((a)=>a.active).length||0} utilizador(es) ativo(s)</p></div><GrowthButton variant="secondary" onClick={()=>setModal('invite')}><Mail className="h-4 w-4"/>Convidar</GrowthButton></div></GrowthCard></div>
    <div className="grid gap-7 lg:grid-cols-[1fr_360px]"><section>{!client.periods?.length?<EmptyGrowth title="Nenhum período criado" description="Cria um período mensal ou personalizado para começar a inserir resultados."/>:<div className="space-y-3">{client.periods.map((period)=><Link key={period.id} href={`/clientes/${id}/periodos/${period.id}`} className="group flex flex-col gap-4 rounded-2xl border border-white/[.08] bg-white/[.04] p-5 hover:border-[#d9ff6a]/25 sm:flex-row sm:items-center"><div className="flex-1"><div className="flex items-center gap-3"><h2 className="font-bold text-white">{period.periodName}</h2><GrowthBadge tone={period.status==='published'?'lime':period.status==='archived'?'neutral':'amber'}>{period.status==='published'?'Publicado':period.status==='archived'?'Arquivado':'Rascunho'}</GrowthBadge></div><p className="mt-2 text-xs text-white/30">{new Date(period.startDate).toLocaleDateString('pt-PT')} — {new Date(period.endDate).toLocaleDateString('pt-PT')}</p></div><div className="grid grid-cols-2 gap-7"><div><p className="text-[10px] uppercase tracking-wider text-white/25">Contactos</p><p className="mt-1 font-bold text-white">{period.contacts}</p></div><div><p className="text-[10px] uppercase tracking-wider text-white/25">Receita</p><p className="mt-1 font-bold text-white">{formatGrowthKz(period.attributedRevenue)}</p></div></div><ArrowRight className="h-4 w-4 text-[#d9ff6a] transition group-hover:translate-x-1"/></Link>)}</div>}</section><aside><GrowthCard><div className="flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-[#d9ff6a]"/><h2 className="text-sm font-bold text-white">Utilizadores convidados</h2></div><div className="mt-5 space-y-3">{client.accesses?.length?client.accesses.map((access)=><div key={access.id} className="flex items-center gap-3 rounded-xl bg-black/15 p-3"><div className="grid h-9 w-9 place-items-center rounded-full bg-white/8 text-xs font-bold text-white/60">{access.user.name.slice(0,2).toUpperCase()}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-white/75">{access.user.name}</p><p className="truncate text-xs text-white/30">{access.user.email}</p></div>{access.active&&<button title="Revogar acesso" onClick={()=>revoke.mutate(access.id)} className="rounded-lg p-2 text-white/25 hover:bg-red-500/10 hover:text-red-200"><UserMinus className="h-4 w-4"/></button>}</div>):<p className="text-sm text-white/35">Ainda não há convidados.</p>}</div></GrowthCard></aside></div>
    {modal&&<div className="fixed inset-0 z-[90] grid place-items-center bg-black/75 p-4 backdrop-blur-sm">{modal==='period'?<PeriodForm template={client.periods?.[0]} busy={createPeriod.isPending} onClose={()=>setModal(null)} onSubmit={(data)=>createPeriod.mutate(data)}/>:<InviteForm busy={invite.isPending} onClose={()=>setModal(null)} onSubmit={(data)=>invite.mutate(data)}/>}</div>}
  </GrowthPage>;
}
function ModalHead({title,onClose}:{title:string;onClose:()=>void}){return <div className="flex items-center justify-between"><h2 className="text-xl font-bold text-white">{title}</h2><button onClick={onClose} type="button" className="rounded-lg p-2 text-white/35 hover:bg-white/5"><X className="h-5 w-5"/></button></div>}
function nextPeriodDefaults(template?:GrowthPeriod){const now=new Date();let first=new Date(Date.UTC(now.getFullYear(),now.getMonth(),1));if(template){const previousEnd=new Date(`${template.endDate.slice(0,10)}T12:00:00Z`);previousEnd.setUTCDate(previousEnd.getUTCDate()+1);first=new Date(Date.UTC(previousEnd.getUTCFullYear(),previousEnd.getUTCMonth(),1))}const last=new Date(Date.UTC(first.getUTCFullYear(),first.getUTCMonth()+1,0));return {periodName:first.toLocaleDateString('pt-PT',{month:'long',year:'numeric',timeZone:'UTC'}),startDate:first.toISOString().slice(0,10),endDate:last.toISOString().slice(0,10),investment:0,contacts:0,qualifiedContacts:0,meetings:0,proposals:0,sales:0,attributedRevenue:0}}
function PeriodForm({template,busy,onClose,onSubmit}:{template?:GrowthPeriod;busy:boolean;onClose:()=>void;onSubmit:(data:Record<string,unknown>)=>void}){const [form,setForm]=useState(()=>nextPeriodDefaults(template));const [reuse,setReuse]=useState(Boolean(template));return <form onSubmit={(e)=>{e.preventDefault();onSubmit({...form,...(reuse&&template?{templatePeriodId:template.id}:{})})}} className="w-full max-w-lg rounded-3xl border border-white/10 bg-[#111713] p-7"><ModalHead title="Novo período" onClose={onClose}/><div className="mt-6 grid gap-4 sm:grid-cols-2"><div className="sm:col-span-2"><GrowthField label="Nome"><input required className={growthInputClass} value={form.periodName} onChange={(e)=>setForm({...form,periodName:e.target.value})}/></GrowthField></div><GrowthField label="Início"><input required type="date" className={growthInputClass} value={form.startDate} onChange={(e)=>setForm({...form,startDate:e.target.value})}/></GrowthField><GrowthField label="Fim"><input required type="date" className={growthInputClass} value={form.endDate} onChange={(e)=>setForm({...form,endDate:e.target.value})}/></GrowthField>{template&&<label className="sm:col-span-2 flex cursor-pointer items-start gap-3 rounded-2xl border border-[#d9ff6a]/20 bg-[#d9ff6a]/[.06] p-4"><input type="checkbox" checked={reuse} onChange={(e)=>setReuse(e.target.checked)} className="mt-1 h-4 w-4 accent-[#d9ff6a]"/><Copy className="mt-0.5 h-4 w-4 shrink-0 text-[#d9ff6a]"/><span><strong className="block text-sm text-white">Usar estrutura de {template.periodName}</strong><small className="mt-1 block leading-5 text-white/45">Copia origens, campanhas e decisões pendentes. Todos os números começam a zero.</small></span></label>}</div><div className="mt-6 flex justify-end gap-3"><GrowthButton type="button" variant="secondary" onClick={onClose}>Cancelar</GrowthButton><GrowthButton disabled={busy}>{busy?'A criar…':'Criar período'}</GrowthButton></div></form>}
function InviteForm({busy,onClose,onSubmit}:{busy:boolean;onClose:()=>void;onSubmit:(data:{name:string;email:string})=>void}){const [name,setName]=useState('');const [email,setEmail]=useState('');return <form onSubmit={(e:FormEvent)=>{e.preventDefault();onSubmit({name,email})}} className="w-full max-w-lg rounded-3xl border border-white/10 bg-[#111713] p-7"><ModalHead title="Convidar cliente" onClose={onClose}/><p className="mt-3 text-sm leading-6 text-white/40">O cliente recebe um link seguro para definir a palavra-passe.</p><div className="mt-6 space-y-4"><GrowthField label="Nome"><input required className={growthInputClass} value={name} onChange={(e)=>setName(e.target.value)}/></GrowthField><GrowthField label="Email"><input required type="email" className={growthInputClass} value={email} onChange={(e)=>setEmail(e.target.value)}/></GrowthField></div><div className="mt-6 flex justify-end gap-3"><GrowthButton type="button" variant="secondary" onClick={onClose}>Cancelar</GrowthButton><GrowthButton disabled={busy}>{busy?'A enviar…':'Enviar convite'}</GrowthButton></div></form>}
