'use client';

import { useQuery } from '@tanstack/react-query';
import ManagementResourcePage from '@/components/management/management-resource-page';
import { KpiCard, StatusBadge } from '@/components/management/management-ui';
import { managementApi, type Campaign } from '@/lib/management-api';
import { formatDate, formatKz, formatPercent } from '@/lib/management-format';

const channels = ['Meta Ads','Google Ads','LinkedIn','Instagram orgânico','Facebook orgânico','Evento','Indicação','Prospecção','Website','Outro'];
export default function MarketingPage() {
  const bootstrap = useQuery({ queryKey: ['management-bootstrap'], queryFn: managementApi.bootstrap });
  const campaigns = useQuery({ queryKey: ['management-campaigns'], queryFn: managementApi.campaigns });
  const profiles = (bootstrap.data?.profiles || []).filter((profile) => ['admin','marketing'].includes(profile.role)).map((profile) => ({ value: profile.id, label: profile.fullName }));
  const rows = campaigns.data || []; const investment = rows.reduce((sum,row) => sum + Number(row.investment),0); const leads = rows.reduce((sum,row) => sum + row.leads,0); const revenue = rows.reduce((sum,row) => sum + Number(row.attributedRevenue),0);
  const fields = [{ name:'name',label:'Nome da campanha',required:true },{ name:'channel',label:'Canal',type:'select' as const,required:true,options:channels.map((value)=>({value,label:value})) },{ name:'objective',label:'Objetivo',type:'select' as const,required:true,options:['Reconhecimento','Tráfego','Leads','Reuniões','Vendas'].map((value)=>({value,label:value})) },{ name:'startDate',label:'Data de início',type:'date' as const,required:true },{ name:'endDate',label:'Data de fim',type:'date' as const },{ name:'status',label:'Estado',type:'select' as const,required:true,options:['planeada','ativa','pausada','concluida','cancelada'].map((value)=>({value,label:value})) },{ name:'responsibleUserId',label:'Responsável',type:'select' as const,options:profiles },{ name:'investment',label:'Investimento (Kz)',type:'number' as const,required:true },{ name:'impressions',label:'Impressões',type:'number' as const },{ name:'reach',label:'Alcance',type:'number' as const },{ name:'clicks',label:'Cliques',type:'number' as const },{ name:'leads',label:'Leads',type:'number' as const },{ name:'qualifiedLeads',label:'Leads qualificados',type:'number' as const },{ name:'meetingsGenerated',label:'Reuniões geradas',type:'number' as const },{ name:'clientsWon',label:'Clientes fechados',type:'number' as const },{ name:'attributedRevenue',label:'Receita atribuída (Kz)',type:'number' as const },{ name:'notes',label:'Observações',type:'textarea' as const }];
  return <ManagementResourcePage<Campaign> title="Marketing" description="Campanhas, investimento, resultados e eficiência." queryKey="management-campaigns" load={managementApi.campaigns} create={managementApi.createCampaign} update={managementApi.updateCampaign} createLabel="Nova campanha" fields={fields} summary={<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><KpiCard label="Investimento" value={formatKz(investment)} tone="amber"/><KpiCard label="Leads" value={leads}/><KpiCard label="CPL" value={leads ? formatKz(investment/leads) : 'Não disponível'}/><KpiCard label="ROAS" value={investment ? `${(revenue/investment).toFixed(2)}x` : 'Não disponível'} tone="green"/></div>} columns={[
    {label:'Campanha',render:(row)=><div><p className="font-semibold">{row.name}</p><p className="text-xs text-slate-500">{row.channel} · {row.objective}</p></div>,searchValue:(row)=>`${row.name} ${row.channel}`},
    {label:'Período',render:(row)=>`${formatDate(row.startDate)} — ${formatDate(row.endDate)}`},{label:'Estado',render:(row)=><StatusBadge value={row.status}/>},{label:'Investimento',render:(row)=>formatKz(row.investment)},{label:'Leads',render:(row)=>row.leads},{label:'CTR',render:(row)=>formatPercent(row.kpis.ctr)},{label:'CPL',render:(row)=>row.kpis.cpl===null?'Não disponível':formatKz(row.kpis.cpl)},{label:'ROAS',render:(row)=>row.kpis.roas===null?'Não disponível':`${row.kpis.roas.toFixed(2)}x`}
  ]} toInitialValues={(row)=>({...row,startDate:row.startDate.slice(0,10),endDate:row.endDate?.slice(0,10)||''})}/>;
}
