'use client';

import { useQuery } from '@tanstack/react-query';
import ManagementResourcePage from '@/components/management/management-resource-page';
import { KpiCard, StatusBadge } from '@/components/management/management-ui';
import { managementApi, type FinancialTransaction } from '@/lib/management-api';
import { formatDate, formatKz, formatPercent } from '@/lib/management-format';

const revenueCategories=['Mensalidade','Projeto','Website','Gestão de marketing','Publicidade','Produção audiovisual','Design','Consultoria','Comissão','Outro'];
const expenseCategories=['Salários','Freelancers','Publicidade','Internet','Escritório','Transporte','Ferramentas','Software','Equipamentos','Produção','Impostos','Outro'];
export default function FinancesPage(){
  const clients=useQuery({queryKey:['management-clients'],queryFn:()=>managementApi.clients()});const transactions=useQuery({queryKey:['management-transactions'],queryFn:()=>managementApi.transactions()});const rows=transactions.data||[];
  const received=rows.filter((row)=>row.type==='receita').reduce((sum,row)=>sum+Number(row.actualValue||0),0);const expected=rows.filter((row)=>row.type==='receita'&&row.status!=='cancelado').reduce((sum,row)=>sum+Number(row.expectedValue||0),0);const expenses=rows.filter((row)=>row.type==='despesa').reduce((sum,row)=>sum+Number(row.actualValue||0),0);const profit=received-expenses;
  const fields=[{name:'date',label:'Data',type:'date' as const,required:true},{name:'type',label:'Tipo',type:'select' as const,required:true,options:[{value:'receita',label:'Receita'},{value:'despesa',label:'Despesa'}]},{name:'category',label:'Categoria',type:'select' as const,required:true,options:Array.from(new Set([...revenueCategories,...expenseCategories])).map((value)=>({value,label:value}))},{name:'subcategory',label:'Subcategoria'},{name:'clientId',label:'Cliente',type:'select' as const,options:(clients.data||[]).map((client)=>({value:client.id,label:client.companyName}))},{name:'project',label:'Projeto'},{name:'description',label:'Descrição',required:true},{name:'expectedValue',label:'Valor previsto (Kz)',type:'number' as const,required:true},{name:'actualValue',label:'Valor realizado (Kz)',type:'number' as const},{name:'dueDate',label:'Data de vencimento',type:'date' as const},{name:'paymentDate',label:'Data de pagamento',type:'date' as const},{name:'status',label:'Estado',type:'select' as const,required:true,options:['previsto','pendente','pago','recebido','parcial','em_atraso','cancelado'].map((value)=>({value,label:value}))},{name:'paymentMethod',label:'Método de pagamento'},{name:'receiptUrl',label:'URL do comprovativo'},{name:'notes',label:'Observações',type:'textarea' as const}];
  return <ManagementResourcePage<FinancialTransaction> title="Finanças" description="Receitas, despesas, contas a receber e rentabilidade." queryKey="management-transactions" load={()=>managementApi.transactions()} create={managementApi.createTransaction} update={managementApi.updateTransaction} remove={managementApi.deleteTransaction} createLabel="Novo movimento" fields={fields} summary={<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5"><KpiCard label="Receita prevista" value={formatKz(expected)}/><KpiCard label="Receita recebida" value={formatKz(received)} tone="green"/><KpiCard label="Despesas pagas" value={formatKz(expenses)} tone="red"/><KpiCard label="Lucro" value={formatKz(profit)} tone={profit>=0?'green':'red'}/><KpiCard label="Margem" value={formatPercent(received?profit/received*100:null)}/></div>} columns={[
    {label:'Data',render:(row)=>formatDate(row.date)},{label:'Tipo',render:(row)=><span className={row.type==='receita'?'font-semibold text-emerald-600':'font-semibold text-red-600'}>{row.type}</span>,searchValue:(row)=>`${row.type} ${row.category} ${row.description}`},{label:'Descrição',render:(row)=><div><p className="font-medium">{row.description}</p><p className="text-xs text-slate-500">{row.client?.companyName||row.project||'—'}</p></div>},{label:'Categoria',render:(row)=>row.category},{label:'Previsto',render:(row)=>formatKz(row.expectedValue)},{label:'Realizado',render:(row)=>formatKz(row.actualValue)},{label:'Estado',render:(row)=><StatusBadge value={row.status}/>}
  ]} toInitialValues={(row)=>({...row,date:row.date.slice(0,10),dueDate:row.dueDate?.slice(0,10)||'',paymentDate:row.paymentDate?.slice(0,10)||''})}/>;
}
