'use client';

import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { CalendarDays, Columns3, List, Plus } from 'lucide-react';
import { Button } from '@/components/ui/button';
import ManagementFormDialog from '@/components/management/management-form-dialog';
import { KpiCard, ManagementEmpty, ManagementLoading, ManagementPage, StatusBadge, tdClass, thClass, tableClass } from '@/components/management/management-ui';
import { managementApi, type OperationalTask } from '@/lib/management-api';
import { formatDate, formatPercent } from '@/lib/management-format';
import { useToast } from '@/components/ui/toast-provider';

const statuses=['pendente','em_producao','revisao_interna','enviado_cliente','revisao_cliente','aprovado','concluido','atrasado','cancelado'];
export default function OperationalPage(){
  const qc=useQueryClient();const {toast}=useToast();const [view,setView]=useState<'table'|'kanban'|'calendar'>('table');const [open,setOpen]=useState(false);const [editing,setEditing]=useState<OperationalTask|null>(null);
  const tasks=useQuery({queryKey:['management-tasks'],queryFn:()=>managementApi.tasks()});const bootstrap=useQuery({queryKey:['management-bootstrap'],queryFn:managementApi.bootstrap});const clients=useQuery({queryKey:['management-clients'],queryFn:()=>managementApi.clients().catch(()=>[])});
  const role=bootstrap.data?.profile.role||'designer';const admin=role==='admin';const people=(bootstrap.data?.profiles||[]).filter((profile)=>['designer','editor','admin'].includes(profile.role)).map((profile)=>({value:profile.id,label:`${profile.fullName} — ${profile.role}`}));
  const save=useMutation({mutationFn:(values:Record<string,unknown>)=>editing?managementApi.updateTask(editing.id,values):managementApi.createTask(values),onSuccess:()=>{qc.invalidateQueries({queryKey:['management-tasks']});setOpen(false);setEditing(null);toast({title:'Trabalho guardado',variant:'success'});}});
  const common=[{name:'status',label:'Estado',type:'select' as const,required:true,options:statuses.map((value)=>({value,label:value.replaceAll('_',' ')}))},{name:'actualHours',label:'Horas utilizadas',type:'number' as const,step:'0.5'},{name:'revisionCount',label:'Número de revisões',type:'number' as const},{name:'clientApproved',label:'Aprovado pelo cliente',type:'checkbox' as const},{name:'delayReason',label:'Motivo de atraso'},{name:'notes',label:'Observações',type:'textarea' as const}];
  const fields=admin?[{name:'clientId',label:'Cliente',type:'select' as const,options:(clients.data||[]).map((client)=>({value:client.id,label:client.companyName}))},{name:'project',label:'Projeto'},{name:'workType',label:'Tipo de trabalho',type:'select' as const,required:true,options:['Flyer','Carrossel','Identidade visual','Apresentação','Website','Vídeo curto','Vídeo longo','Reels','Captação','Animação','Outro'].map((value)=>({value,label:value}))},{name:'title',label:'Título',required:true},{name:'description',label:'Descrição',type:'textarea' as const},{name:'responsibleUserId',label:'Responsável',type:'select' as const,options:people},{name:'requestDate',label:'Data de solicitação',type:'date' as const,required:true},{name:'startDate',label:'Data de início',type:'date' as const},{name:'deadline',label:'Prazo',type:'datetime-local' as const,required:true},{name:'priority',label:'Prioridade',type:'select' as const,required:true,options:['baixa','normal','alta','urgente'].map((value)=>({value,label:value}))},{name:'estimatedHours',label:'Horas estimadas',type:'number' as const,step:'0.5'},...common]:common;
  if(tasks.isLoading||bootstrap.isLoading)return <ManagementLoading/>;const rows=tasks.data||[];const completed=rows.filter((row)=>row.status==='concluido');const delayed=rows.filter((row)=>row.status==='atrasado');const onTime=completed.filter((row)=>row.deliveredOnTime).length;
  const edit=(row:OperationalTask)=>{setEditing(row);setOpen(true)};
  return <ManagementPage title="Operacional" description="Trabalhos, horas, revisões e cumprimento de prazos." action={<div className="flex flex-wrap gap-2"><div className="flex rounded-lg border border-slate-200 p-1 dark:border-slate-700">{([['table',List],['kanban',Columns3],['calendar',CalendarDays]] as const).map(([key,Icon])=><button key={key} onClick={()=>setView(key)} className={`rounded-md p-2 ${view===key?'bg-blue-600 text-white':'text-slate-500'}`}><Icon className="h-4 w-4"/></button>)}</div>{admin&&<Button onClick={()=>{setEditing(null);setOpen(true)}}><Plus className="mr-2 h-4 w-4"/>Novo trabalho</Button>}</div>}>
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5"><KpiCard label="Total" value={rows.length}/><KpiCard label="Concluídos" value={completed.length} tone="green"/><KpiCard label="Pendentes" value={rows.filter((row)=>row.status==='pendente').length} tone="amber"/><KpiCard label="Atrasados" value={delayed.length} tone="red"/><KpiCard label="No prazo" value={formatPercent(completed.length?onTime/completed.length*100:null)}/></div>
    {rows.length===0?<ManagementEmpty/>:view==='table'?<div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900"><table className={tableClass}><thead><tr>{['Trabalho','Cliente','Responsável','Prazo','Prioridade','Estado','Horas'].map((label)=><th className={thClass} key={label}>{label}</th>)}</tr></thead><tbody>{rows.map((row)=><tr key={row.id} onClick={()=>edit(row)} className="cursor-pointer hover:bg-slate-50 dark:hover:bg-slate-800"> <td className={tdClass}><p className="font-semibold">{row.title}</p><p className="text-xs text-slate-500">{row.workType}</p></td><td className={tdClass}>{row.client?.companyName||'—'}</td><td className={tdClass}>{row.responsible?.fullName||'—'}</td><td className={tdClass}>{formatDate(row.deadline)}</td><td className={tdClass}>{row.priority}</td><td className={tdClass}><StatusBadge value={row.status}/></td><td className={tdClass}>{Number(row.actualHours||0)}h / {Number(row.estimatedHours||0)}h</td></tr>)}</tbody></table></div>:view==='kanban'?<div className="flex gap-4 overflow-x-auto pb-4">{statuses.map((status)=><section key={status} className="min-h-72 w-64 flex-none rounded-2xl bg-slate-100 p-3 dark:bg-slate-900"><h2 className="mb-3 text-sm font-bold">{status.replaceAll('_',' ')}</h2>{rows.filter((row)=>row.status===status).map((row)=><button onClick={()=>edit(row)} key={row.id} className="mb-2 w-full rounded-xl bg-white p-3 text-left shadow-sm dark:bg-slate-800"><p className="font-semibold">{row.title}</p><p className="mt-1 text-xs text-slate-500">{row.responsible?.fullName}</p><p className="mt-2 text-xs">Prazo: {formatDate(row.deadline)}</p></button>)}</section>)}</div>:<div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{[...rows].sort((a,b)=>a.deadline.localeCompare(b.deadline)).map((row)=><button onClick={()=>edit(row)} key={row.id} className="rounded-2xl border border-slate-200 bg-white p-4 text-left dark:border-slate-800 dark:bg-slate-900"><p className="text-xs font-bold uppercase text-blue-600">{formatDate(row.deadline)}</p><p className="mt-2 font-semibold">{row.title}</p><p className="text-sm text-slate-500">{row.client?.companyName||row.project||'Sem projeto'}</p><div className="mt-3"><StatusBadge value={row.status}/></div></button>)}</div>}
    <ManagementFormDialog open={open} onOpenChange={setOpen} title={editing?'Atualizar trabalho':'Novo trabalho'} fields={fields} initialValues={editing?{...editing,requestDate:editing.requestDate.slice(0,10),startDate:editing.startDate?.slice(0,10)||'',deadline:editing.deadline.slice(0,16)}:{requestDate:new Date().toISOString().slice(0,10),priority:'normal',status:'pendente',revisionCount:0}} isEditing={Boolean(editing)} submitting={save.isPending} onSubmit={(values)=>save.mutateAsync(values)}/>
  </ManagementPage>;
}
