'use client';

import Link from 'next/link';
import { useEffect, useRef, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { AlertTriangle, ArrowLeft, ArrowRight, Calculator, Check, CircleDot, Eye, Plus, Save, Send, Sparkles, Trash2 } from 'lucide-react';
import { GrowthBadge, GrowthButton, GrowthCard, GrowthField, GrowthPage, growthInputClass, growthTextareaClass } from '@/components/growth/growth-ui';
import { GrowthCampaign, GrowthContactSource, GrowthDecision, GrowthPeriod, growthApi } from '@/lib/growth-api';

const tabs = [['numbers','Números gerais'],['origins','Origens'],['funnel','Funil'],['campaigns','Campanhas'],['reading','Leitura estratégica'],['decisions','Próximas decisões'],['report','Relatório']] as const;
const quickTabKeys:Tab[]=['numbers','origins','campaigns','reading'];
type Tab = typeof tabs[number][0];
const blankSource:GrowthContactSource={sourceName:'',contacts:0,qualifiedContacts:0,meetings:0,proposals:0,sales:0,revenue:0,qualityLabel:'medium',strategicReading:'',sortOrder:0};
const blankCampaign:GrowthCampaign={name:'',objective:'',sourceName:'',investment:0,contacts:0,sales:0,revenue:0,status:'testing',decision:'',note:'',sortOrder:0};
const blankDecision:GrowthDecision={decision:'',reason:'',owner:'Mazanga',priority:'medium',status:'next_action',expectedImpact:'',sortOrder:0};

const sourcePresets = ['Meta Ads', 'Google Ads', 'Orgânico', 'Referências'];
const sum = <T,>(rows:T[], key:keyof T) => rows.reduce((total,row)=>total+Number(row[key]||0),0);
const hasText = (value:unknown) => Boolean(String(value||'').trim());

function suggestedNarrative(form:GrowthPeriod){
  const bottleneckStage=form.metrics.funnel.find((stage)=>stage.key===form.metrics.suggestedBottleneck);
  const bottleneck=bottleneckStage?.label||'etapa com maior queda';
  const returnText=form.metrics.estimatedReturn==null?'ainda sem retorno calculável':`retorno estimado de ${form.metrics.estimatedReturn.toFixed(1)}x`;
  const summary=`No período ${form.periodName}, foram gerados ${form.contacts} contactos, ${form.proposals} propostas e ${form.sales} vendas, com ${returnText}.`;
  const recommendation=form.sales>0?'Concentrar investimento nas origens e campanhas com melhor conversão e acompanhar semanalmente a passagem até à venda.':'Rever a qualidade dos contactos e acelerar o acompanhamento comercial antes de aumentar o investimento.';
  return {
    summary,
    bottleneck:`O principal ponto de atenção está em ${bottleneck}. A equipa deve validar a qualidade da passagem para a etapa seguinte.`,
    recommendation,
    reading:{
      whatHappened:summary,
      whatDataShows:`Os dados mostram ${form.qualifiedContacts} contactos qualificados, ${form.meetings} reuniões e ${form.sales} vendas.`,
      bottleneck:`A maior queda do funil foi identificada em ${bottleneck}.`,
      businessMeaning:form.sales>0?'Existe procura convertida em receita; o ganho seguinte virá de melhorar a eficiência do funil.':'A geração de procura ainda não está a transformar-se em vendas com consistência.',
      recommendedDecision:recommendation,
      nextActions:'Acompanhar as conversões por origem, rever os contactos sem avanço e atualizar as decisões na próxima reunião.',
      clientNeeds:'Garantir retorno rápido aos contactos e partilhar com a Mazanga o resultado das propostas e vendas.',
    },
    report:{
      executiveSummary:summary,
      mainLearnings:`O maior espaço de melhoria está em ${bottleneck}.`,
      whatWorked:form.sales>0?`${form.sales} venda${form.sales===1?' foi concluída':'s foram concluídas'} no período.`:'Os canais mantiveram a geração de contactos durante o período.',
      whatDidNotWork:`A passagem por ${bottleneck} ficou abaixo do potencial esperado.`,
      decisionsTaken:recommendation,
      nextSteps:'Executar as próximas decisões, acompanhar semanalmente o funil e comparar os resultados no período seguinte.',
    },
  };
}

export default function PeriodEditorPage(){
  const params=useParams();const id=String(params.id);const periodId=String(params.periodId);const router=useRouter();const qc=useQueryClient();
  const [tab,setTab]=useState<Tab>('numbers');const [mode,setMode]=useState<'quick'|'complete'>('quick');const [autoSync,setAutoSync]=useState(false);const [form,setForm]=useState<GrowthPeriod|null>(null);const [dirty,setDirty]=useState(false);const [saveState,setSaveState]=useState<'idle'|'saving'|'saved'|'error'>('idle');const loaded=useRef(false);const revision=useRef(0);
  const query=useQuery({queryKey:['growth-period',periodId],queryFn:()=>growthApi.period(periodId)});
  const save=useMutation({mutationFn:({data}:{data:Record<string,unknown>;revision:number})=>growthApi.updatePeriod(periodId,data),onMutate:()=>setSaveState('saving'),onSuccess:(data,variables)=>{if(revision.current===variables.revision){setForm(data);setDirty(false);setSaveState('saved')}qc.invalidateQueries({queryKey:['growth-client',id]})},onError:()=>setSaveState('error')});
  const publish=useMutation({mutationFn:()=>growthApi.publish(periodId),onSuccess:()=>{qc.invalidateQueries({queryKey:['growth-period',periodId]});qc.invalidateQueries({queryKey:['growth-client',id]});setSaveState('saved')}});
  const archive=useMutation({mutationFn:()=>growthApi.archive(periodId),onSuccess:()=>router.push(`/clientes/${id}`)});
  const remove=useMutation({mutationFn:()=>growthApi.removePeriod(periodId),onSuccess:()=>router.push(`/clientes/${id}`)});
  useEffect(()=>{if(query.data&&!loaded.current){setForm(query.data);loaded.current=true}},[query.data]);
  useEffect(()=>{if(!dirty||!form||save.isPending)return;const timer=window.setTimeout(()=>save.mutate({data:payload(form),revision:revision.current}),900);return()=>window.clearTimeout(timer)},[dirty,form,save.isPending]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(()=>{const warn=(event:BeforeUnloadEvent)=>{if(dirty||save.isPending){event.preventDefault();event.returnValue=''}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[dirty,save.isPending]);
  useEffect(()=>{if(!autoSync)return;setForm((old)=>{if(!old)return old;const sourceValues=old.sources.length?{contacts:sum(old.sources,'contacts'),qualifiedContacts:sum(old.sources,'qualifiedContacts'),meetings:sum(old.sources,'meetings'),proposals:sum(old.sources,'proposals'),sales:sum(old.sources,'sales'),attributedRevenue:sum(old.sources,'revenue')}:{contacts:old.contacts,qualifiedContacts:old.qualifiedContacts,meetings:old.meetings,proposals:old.proposals,sales:old.sales,attributedRevenue:Number(old.attributedRevenue)};const investment=old.campaigns.length?sum(old.campaigns,'investment'):Number(old.investment);const changed=Object.entries(sourceValues).some(([key,value])=>Number(old[key as keyof GrowthPeriod])!==value)||Number(old.investment)!==investment;if(!changed)return old;revision.current+=1;setDirty(true);setSaveState('idle');return {...old,...sourceValues,investment}})},[autoSync,form?.sources,form?.campaigns]);
  const change=<K extends keyof GrowthPeriod>(key:K,value:GrowthPeriod[K])=>{revision.current+=1;setForm((old)=>old?{...old,[key]:value}:old);setDirty(true);setSaveState('idle')};
  if(!form)return <div className="p-10 text-white/40">A preparar o editor…</div>;
  const status=saveState==='saving'?'A guardar…':saveState==='error'?'Erro ao guardar':saveState==='saved'?'Guardado':'Alterações automáticas';
  const visibleTabs=mode==='quick'?tabs.filter(([key])=>quickTabKeys.includes(key)):tabs;
  const tabIndex=visibleTabs.findIndex(([key])=>key===tab);
  return <GrowthPage eyebrow={`${form.client?.companyName||'Cliente'} · Editor de período`} title={form.periodName} description="Constrói a leitura por etapas. A última versão publicada continua visível enquanto trabalhas neste rascunho." action={<div className="flex flex-wrap items-center gap-3"><span className={`inline-flex items-center gap-2 text-xs ${saveState==='error'?'text-red-300':'text-white/35'}`}>{saveState==='saving'?<Save className="h-3.5 w-3.5 animate-pulse"/>:<Check className="h-3.5 w-3.5"/>}{status}</span>{form.publications?.length?<Link href={`/sala?clientId=${id}&periodId=${periodId}`} className="inline-flex h-11 items-center gap-2 rounded-xl border border-white/10 bg-white/5 px-4 text-sm font-bold text-white hover:bg-white/10"><Eye className="h-4 w-4"/>Pré-visualizar</Link>:null}<GrowthButton disabled={publish.isPending||dirty||save.isPending} onClick={()=>publish.mutate()}><Send className="h-4 w-4"/>{publish.isPending?'A publicar…':'Publicar'}</GrowthButton><Link href={`/clientes/${id}`} className="rounded-xl border border-white/10 p-3 text-white/45 hover:text-white"><ArrowLeft className="h-4 w-4"/></Link></div>}>
    {form.warnings?.length>0&&<div className="mb-5 rounded-2xl border border-amber-300/15 bg-amber-300/[.06] p-4"><div className="flex items-center gap-2 text-sm font-bold text-amber-200"><AlertTriangle className="h-4 w-4"/>Verificações recomendadas</div><ul className="mt-2 list-disc space-y-1 pl-5 text-xs leading-5 text-amber-100/55">{form.warnings.map((warning)=><li key={warning}>{warning}</li>)}</ul></div>}
    <div className="mb-4 flex w-fit rounded-xl border border-white/10 bg-black/15 p-1"><button type="button" onClick={()=>{setMode('quick');if(!quickTabKeys.includes(tab))setTab('numbers')}} className={`rounded-lg px-4 py-2 text-xs font-bold ${mode==='quick'?'bg-white/10 text-white':'text-white/35'}`}>Preenchimento rápido</button><button type="button" onClick={()=>setMode('complete')} className={`rounded-lg px-4 py-2 text-xs font-bold ${mode==='complete'?'bg-white/10 text-white':'text-white/35'}`}>Editor completo</button></div>
    <SmartAssistant form={form} change={change} autoSync={autoSync} onAutoSync={setAutoSync}/>
    <div className="mb-6 flex gap-2 overflow-x-auto pb-2">{visibleTabs.map(([key,label],index)=><button key={key} onClick={()=>setTab(key)} className={`whitespace-nowrap rounded-full border px-4 py-2 text-xs font-bold transition ${tab===key?'border-[#d9ff6a] bg-[#d9ff6a] text-[#0c110d]':'border-white/10 bg-white/[.03] text-white/40 hover:text-white'}`}>{index+1}. {mode==='quick'&&key==='reading'?'Conclusão':label}</button>)}</div>
    {tab==='numbers'&&<Numbers form={form} change={change}/>} {tab==='origins'&&<Sources form={form} change={change}/>} {tab==='funnel'&&<Funnel form={form} change={change}/>} {tab==='campaigns'&&<Campaigns form={form} change={change}/>} {tab==='reading'&&<Reading form={form} change={change}/>} {tab==='decisions'&&<Decisions form={form} change={change}/>} {tab==='report'&&<Report form={form} change={change}/>} 
    <div className="mt-6 flex items-center justify-between gap-3"><GrowthButton variant="secondary" disabled={tabIndex===0} onClick={()=>setTab(visibleTabs[Math.max(0,tabIndex-1)][0])}><ArrowLeft className="h-4 w-4"/>Anterior</GrowthButton>{tabIndex<visibleTabs.length-1?<GrowthButton onClick={()=>setTab(visibleTabs[tabIndex+1][0])}>Continuar<ArrowRight className="h-4 w-4"/></GrowthButton>:<GrowthButton disabled={publish.isPending||dirty||save.isPending} onClick={()=>publish.mutate()}><Send className="h-4 w-4"/>Publicar período</GrowthButton>}</div>
    <div className="mt-8 flex flex-wrap items-center justify-between gap-3 border-t border-white/[.07] pt-6"><div className="flex gap-3">{form.publications?.length?<GrowthButton variant="secondary" onClick={()=>archive.mutate()}>Arquivar período</GrowthButton>:<GrowthButton variant="danger" onClick={()=>{if(confirm('Eliminar este rascunho?'))remove.mutate()}}><Trash2 className="h-4 w-4"/>Eliminar rascunho</GrowthButton>}</div><GrowthBadge tone={form.publications?.length?'lime':'amber'}>{form.publications?.length?`Última publicação v${form.publications[0].version}`:'Nunca publicado'}</GrowthBadge></div>
  </GrowthPage>;
}
function payload(form:GrowthPeriod):Record<string,unknown>{return {periodName:form.periodName,startDate:form.startDate.slice(0,10),endDate:form.endDate.slice(0,10),investment:Number(form.investment),contacts:Number(form.contacts),qualifiedContacts:Number(form.qualifiedContacts),meetings:Number(form.meetings),proposals:Number(form.proposals),sales:Number(form.sales),attributedRevenue:Number(form.attributedRevenue),executiveSummary:form.executiveSummary||null,mainBottleneck:form.mainBottleneck||null,recommendation:form.recommendation||null,sources:form.sources,campaigns:form.campaigns,strategicReading:form.strategicReading||{},decisions:form.decisions,report:form.report||{}}}
type Change=<K extends keyof GrowthPeriod>(key:K,value:GrowthPeriod[K])=>void;
function SmartAssistant({form,change,autoSync,onAutoSync}:{form:GrowthPeriod;change:Change;autoSync:boolean;onAutoSync:(value:boolean)=>void}){
  const sourceTotals={contacts:sum(form.sources,'contacts'),qualifiedContacts:sum(form.sources,'qualifiedContacts'),meetings:sum(form.sources,'meetings'),proposals:sum(form.sources,'proposals'),sales:sum(form.sources,'sales'),attributedRevenue:sum(form.sources,'revenue')};
  const campaignInvestment=sum(form.campaigns,'investment');
  const narrative=suggestedNarrative(form);
  const completed=[hasText(form.executiveSummary),form.sources.length>0,hasText(form.mainBottleneck),form.campaigns.length>0,hasText(form.strategicReading?.whatDataShows),form.decisions.length>0,hasText(form.report?.executiveSummary)].filter(Boolean).length;
  const syncSources=()=>{change('contacts',sourceTotals.contacts);change('qualifiedContacts',sourceTotals.qualifiedContacts);change('meetings',sourceTotals.meetings);change('proposals',sourceTotals.proposals);change('sales',sourceTotals.sales);change('attributedRevenue',sourceTotals.attributedRevenue)};
  const completeTexts=()=>{
    if(!hasText(form.executiveSummary))change('executiveSummary',narrative.summary);
    if(!hasText(form.mainBottleneck))change('mainBottleneck',narrative.bottleneck);
    if(!hasText(form.recommendation))change('recommendation',narrative.recommendation);
    const reading=form.strategicReading||{};
    change('strategicReading',Object.fromEntries(Object.entries(narrative.reading).map(([key,value])=>[key,hasText(reading[key as keyof typeof reading])?reading[key as keyof typeof reading]:value])));
    const report=form.report||{};
    change('report',Object.fromEntries(Object.entries(narrative.report).map(([key,value])=>[key,hasText(report[key as keyof typeof report])?report[key as keyof typeof report]:value])));
    if(!form.decisions.length)change('decisions',[{...blankDecision,decision:narrative.recommendation,reason:`Melhorar ${form.metrics.funnel.find((stage)=>stage.key===form.metrics.suggestedBottleneck)?.label||'o funil'}.`,expectedImpact:'Aumentar a conversão e tornar o investimento mais eficiente.'}]);
  };
  return <div className="mb-6 overflow-hidden rounded-3xl border border-[#d9ff6a]/20 bg-gradient-to-br from-[#d9ff6a]/10 to-transparent p-5 md:p-6">
    <div className="flex flex-col gap-5 xl:flex-row xl:items-center xl:justify-between"><div><div className="flex items-center gap-2 text-sm font-extrabold text-white"><Sparkles className="h-4 w-4 text-[#d9ff6a]"/>Assistente de preenchimento</div><p className="mt-2 max-w-2xl text-xs leading-5 text-white/50">Preenche o detalhe uma vez e usa estes atalhos para atualizar os totais e preparar os textos. Tudo continua editável antes da publicação.</p></div><div className="flex items-center gap-3"><div className="h-2 w-28 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-[#d9ff6a] transition-all" style={{width:`${Math.round(completed/7*100)}%`}}/></div><span className="whitespace-nowrap text-xs font-bold text-white/55">{completed}/7 secções preparadas</span></div></div>
    <div className="mt-5 grid gap-3 md:grid-cols-3"><button type="button" disabled={!form.sources.length} onClick={syncSources} className="flex items-center gap-3 rounded-2xl border border-white/10 bg-black/15 p-4 text-left transition hover:border-[#d9ff6a]/35 hover:bg-white/[.06] disabled:cursor-not-allowed disabled:opacity-35"><Calculator className="h-5 w-5 shrink-0 text-[#d9ff6a]"/><span><strong className="block text-sm text-white">Somar origens</strong><small className="mt-1 block text-white/40">Atualiza contactos, funil e receita</small></span></button><button type="button" disabled={!form.campaigns.length} onClick={()=>change('investment',campaignInvestment)} className="flex items-center gap-3 rounded-2xl border border-white/10 bg-black/15 p-4 text-left transition hover:border-[#d9ff6a]/35 hover:bg-white/[.06] disabled:cursor-not-allowed disabled:opacity-35"><Calculator className="h-5 w-5 shrink-0 text-[#d9ff6a]"/><span><strong className="block text-sm text-white">Somar investimento</strong><small className="mt-1 block text-white/40">Usa o total das campanhas</small></span></button><button type="button" onClick={completeTexts} className="flex items-center gap-3 rounded-2xl border border-[#d9ff6a]/25 bg-[#d9ff6a]/10 p-4 text-left transition hover:bg-[#d9ff6a]/15"><Sparkles className="h-5 w-5 shrink-0 text-[#d9ff6a]"/><span><strong className="block text-sm text-white">Completar textos</strong><small className="mt-1 block text-white/50">Gera sugestões nos campos vazios</small></span></button></div>
    <label className="mt-4 flex cursor-pointer items-center gap-3 text-xs text-white/55"><input type="checkbox" checked={autoSync} onChange={(event)=>onAutoSync(event.target.checked)} className="h-4 w-4 accent-[#d9ff6a]"/><span><strong className="text-white/75">Manter totais sincronizados</strong> — alterações nas origens e campanhas atualizam automaticamente os números gerais.</span></label>
  </div>;
}
function NumberField({label,value,onChange}:{label:string;value:number|string;onChange:(v:number)=>void}){return <GrowthField label={label}><input type="number" min="0" inputMode="decimal" className={growthInputClass} value={value} onFocus={(event)=>event.currentTarget.select()} onChange={(e)=>onChange(Number(e.target.value))}/></GrowthField>}
function Numbers({form,change}:{form:GrowthPeriod;change:Change}){return <GrowthCard><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4"><GrowthField label="Nome do período"><input className={growthInputClass} value={form.periodName} onChange={(e)=>change('periodName',e.target.value)}/></GrowthField><GrowthField label="Início"><input type="date" className={growthInputClass} value={form.startDate.slice(0,10)} onChange={(e)=>change('startDate',e.target.value)}/></GrowthField><GrowthField label="Fim"><input type="date" className={growthInputClass} value={form.endDate.slice(0,10)} onChange={(e)=>change('endDate',e.target.value)}/></GrowthField><NumberField label="Investimento (Kz)" value={form.investment} onChange={(v)=>change('investment',v)}/><NumberField label="Contactos recebidos" value={form.contacts} onChange={(v)=>change('contacts',v)}/><NumberField label="Contactos qualificados" value={form.qualifiedContacts} onChange={(v)=>change('qualifiedContacts',v)}/><NumberField label="Reuniões" value={form.meetings} onChange={(v)=>change('meetings',v)}/><NumberField label="Propostas" value={form.proposals} onChange={(v)=>change('proposals',v)}/><NumberField label="Vendas" value={form.sales} onChange={(v)=>change('sales',v)}/><NumberField label="Receita atribuída (Kz)" value={form.attributedRevenue} onChange={(v)=>change('attributedRevenue',v)}/><div className="md:col-span-2 xl:col-span-4"><GrowthField label="Resumo da Mazanga"><textarea className={growthTextareaClass} value={form.executiveSummary||''} onChange={(e)=>change('executiveSummary',e.target.value)} placeholder="Explica o que estes números significam para o cliente…"/></GrowthField></div></div></GrowthCard>}
function Sources({form,change}:{form:GrowthPeriod;change:Change}){const update=(i:number,key:keyof GrowthContactSource,value:unknown)=>change('sources',form.sources.map((row,index)=>index===i?{...row,[key]:value}:row));const add=(sourceName='')=>change('sources',[...form.sources,{...blankSource,sourceName,sortOrder:form.sources.length}]);return <div className="space-y-4">{form.sources.map((row,i)=><GrowthCard key={row.id||i}><div className="mb-4 flex justify-between"><p className="text-sm font-bold text-white">Origem {i+1}</p><button onClick={()=>change('sources',form.sources.filter((_,index)=>index!==i))} className="text-white/25 hover:text-red-200"><Trash2 className="h-4 w-4"/></button></div><div className="grid gap-4 md:grid-cols-3 xl:grid-cols-4"><GrowthField label="Origem"><input className={growthInputClass} value={row.sourceName} onChange={(e)=>update(i,'sourceName',e.target.value)}/></GrowthField>{[['contacts','Contactos'],['qualifiedContacts','Qualificados'],['meetings','Reuniões'],['proposals','Propostas'],['sales','Vendas'],['revenue','Receita (Kz)']].map(([key,label])=><NumberField key={key} label={label} value={Number(row[key as keyof GrowthContactSource]||0)} onChange={(v)=>update(i,key as keyof GrowthContactSource,v)}/>)}<GrowthField label="Qualidade"><select className={growthInputClass} value={row.qualityLabel} onChange={(e)=>update(i,'qualityLabel',e.target.value)}><option value="low">Baixa</option><option value="medium">Média</option><option value="high">Alta</option><option value="very_high">Muito alta</option></select></GrowthField><div className="md:col-span-3 xl:col-span-4"><GrowthField label="Leitura"><textarea className={growthTextareaClass} value={row.strategicReading||''} onChange={(e)=>update(i,'strategicReading',e.target.value)}/></GrowthField></div></div></GrowthCard>)}<div className="flex flex-wrap items-center gap-2"><GrowthButton variant="secondary" onClick={()=>add()}><Plus className="h-4 w-4"/>Adicionar origem</GrowthButton>{sourcePresets.filter((name)=>!form.sources.some((source)=>source.sourceName===name)).map((name)=><button type="button" key={name} onClick={()=>add(name)} className="rounded-full border border-white/10 px-3 py-2 text-xs font-semibold text-white/45 hover:border-[#d9ff6a]/30 hover:text-white">+ {name}</button>)}</div></div>}
function Funnel({form,change}:{form:GrowthPeriod;change:Change}){return <div className="space-y-5"><div className="grid gap-3 md:grid-cols-5">{form.metrics.funnel.map((stage,index)=><GrowthCard key={stage.key} className="relative"><p className="text-[10px] font-bold uppercase tracking-wider text-white/30">{stage.label}</p><p className="mt-3 text-3xl font-extrabold text-white">{stage.value}</p>{index>0&&<p className="mt-2 text-xs text-white/35">{stage.conversion==null?'—':`${(stage.conversion*100).toFixed(1)}%`} conversão · queda {stage.drop}</p>}{form.metrics.suggestedBottleneck===stage.key&&<CircleDot className="absolute right-4 top-4 h-4 w-4 text-amber-300"/>}</GrowthCard>)}</div><GrowthCard><GrowthField label="Maior gargalo — leitura da Mazanga"><textarea className={growthTextareaClass} value={form.mainBottleneck||''} onChange={(e)=>change('mainBottleneck',e.target.value)} placeholder="O maior gargalo está entre…"/></GrowthField></GrowthCard></div>}
function Campaigns({form,change}:{form:GrowthPeriod;change:Change}){const update=(i:number,key:keyof GrowthCampaign,value:unknown)=>change('campaigns',form.campaigns.map((row,index)=>index===i?{...row,[key]:value}:row));return <div className="space-y-4">{form.campaigns.map((row,i)=><GrowthCard key={row.id||i}><div className="mb-4 flex justify-between"><p className="text-sm font-bold text-white">Campanha {i+1}</p><button onClick={()=>change('campaigns',form.campaigns.filter((_,index)=>index!==i))} className="text-white/25 hover:text-red-200"><Trash2 className="h-4 w-4"/></button></div><div className="grid gap-4 md:grid-cols-3"><GrowthField label="Nome"><input className={growthInputClass} value={row.name} onChange={(e)=>update(i,'name',e.target.value)}/></GrowthField><GrowthField label="Objetivo"><input className={growthInputClass} value={row.objective||''} onChange={(e)=>update(i,'objective',e.target.value)}/></GrowthField><GrowthField label="Canal"><input className={growthInputClass} value={row.sourceName||''} onChange={(e)=>update(i,'sourceName',e.target.value)}/></GrowthField><NumberField label="Investimento" value={row.investment} onChange={(v)=>update(i,'investment',v)}/><NumberField label="Contactos" value={row.contacts} onChange={(v)=>update(i,'contacts',v)}/><NumberField label="Vendas" value={row.sales} onChange={(v)=>update(i,'sales',v)}/><NumberField label="Receita" value={row.revenue} onChange={(v)=>update(i,'revenue',v)}/><GrowthField label="Estado"><select className={growthInputClass} value={row.status} onChange={(e)=>update(i,'status',e.target.value)}><option value="testing">Em teste</option><option value="maintain">A manter</option><option value="scale">A escalar</option><option value="optimize">A otimizar</option><option value="pause">A pausar</option><option value="finished">Finalizada</option></select></GrowthField><GrowthField label="Decisão"><input className={growthInputClass} value={row.decision||''} onChange={(e)=>update(i,'decision',e.target.value)}/></GrowthField><div className="md:col-span-3"><GrowthField label="Nota"><textarea className={growthTextareaClass} value={row.note||''} onChange={(e)=>update(i,'note',e.target.value)}/></GrowthField></div></div></GrowthCard>)}<GrowthButton variant="secondary" onClick={()=>change('campaigns',[...form.campaigns,{...blankCampaign,sortOrder:form.campaigns.length}])}><Plus className="h-4 w-4"/>Adicionar campanha</GrowthButton></div>}
function Reading({form,change}:{form:GrowthPeriod;change:Change}){const reading=form.strategicReading||{};const update=(key:string,value:string)=>change('strategicReading',{...reading,[key]:value});const fields=[['whatHappened','O que aconteceu'],['whatDataShows','O que os dados mostram'],['bottleneck','Onde está o gargalo'],['businessMeaning','O que isto significa para o negócio'],['recommendedDecision','Decisão recomendada'],['nextActions','Próximas ações da Mazanga'],['clientNeeds','O que precisamos do cliente']] as const;return <div className="grid gap-4 lg:grid-cols-2">{fields.map(([key,label],index)=><GrowthCard key={key} className={index===3||index===4?'lg:col-span-2':''}><GrowthField label={label}><textarea className={growthTextareaClass} value={reading[key]||''} onChange={(e)=>update(key,e.target.value)}/></GrowthField></GrowthCard>)}</div>}
function Decisions({form,change}:{form:GrowthPeriod;change:Change}){const update=(i:number,key:keyof GrowthDecision,value:unknown)=>change('decisions',form.decisions.map((row,index)=>index===i?{...row,[key]:value}:row));return <div className="space-y-4">{form.decisions.map((row,i)=><GrowthCard key={row.id||i}><div className="mb-4 flex justify-between"><p className="text-sm font-bold text-white">Decisão {i+1}</p><button onClick={()=>change('decisions',form.decisions.filter((_,index)=>index!==i))} className="text-white/25 hover:text-red-200"><Trash2 className="h-4 w-4"/></button></div><div className="grid gap-4 md:grid-cols-2"><GrowthField label="Decisão"><input className={growthInputClass} value={row.decision} onChange={(e)=>update(i,'decision',e.target.value)}/></GrowthField><GrowthField label="Responsável"><input className={growthInputClass} value={row.owner||''} onChange={(e)=>update(i,'owner',e.target.value)}/></GrowthField><GrowthField label="Prioridade"><select className={growthInputClass} value={row.priority} onChange={(e)=>update(i,'priority',e.target.value)}><option value="low">Baixa</option><option value="medium">Média</option><option value="high">Alta</option></select></GrowthField><GrowthField label="Estado"><select className={growthInputClass} value={row.status} onChange={(e)=>update(i,'status',e.target.value)}><option value="next_action">Próxima ação</option><option value="in_progress">Em curso</option><option value="completed">Concluída</option><option value="cancelled">Cancelada</option></select></GrowthField><GrowthField label="Motivo"><textarea className={growthTextareaClass} value={row.reason||''} onChange={(e)=>update(i,'reason',e.target.value)}/></GrowthField><GrowthField label="Impacto esperado"><textarea className={growthTextareaClass} value={row.expectedImpact||''} onChange={(e)=>update(i,'expectedImpact',e.target.value)}/></GrowthField></div></GrowthCard>)}<GrowthButton variant="secondary" onClick={()=>change('decisions',[...form.decisions,{...blankDecision,sortOrder:form.decisions.length}])}><Plus className="h-4 w-4"/>Adicionar decisão</GrowthButton></div>}
function Report({form,change}:{form:GrowthPeriod;change:Change}){const report=form.report||{};const update=(key:string,value:string)=>change('report',{...report,[key]:value});const fields=[['executiveSummary','Resumo executivo'],['mainLearnings','Principais aprendizados'],['whatWorked','O que funcionou'],['whatDidNotWork','O que não funcionou'],['decisionsTaken','Decisões tomadas'],['nextSteps','Próximos passos']] as const;return <GrowthCard><div className="grid gap-5 lg:grid-cols-2">{fields.map(([key,label])=><GrowthField key={key} label={label}><textarea className={growthTextareaClass} value={report[key]||''} onChange={(e)=>update(key,e.target.value)}/></GrowthField>)}</div></GrowthCard>}
