'use client';

import { useQuery } from '@tanstack/react-query';
import ManagementResourcePage from '@/components/management/management-resource-page';
import { StatusBadge } from '@/components/management/management-ui';
import { managementApi, type Goal } from '@/lib/management-api';
import { formatKz, formatPercent } from '@/lib/management-format';

const kpis=[['revenueReceived','Receita recebida'],['revenueExpected','Receita prevista'],['expenses','Despesas'],['profit','Lucro'],['profitMargin','Margem de lucro'],['mrr','MRR'],['activeClients','Clientes ativos'],['newClients','Novos clientes'],['lostClients','Clientes perdidos'],['leads','Leads'],['qualifiedLeads','Leads qualificados'],['meetings','Reuniões'],['proposals','Propostas'],['won','Clientes fechados'],['closeRate','Taxa de fecho'],['pipelineValue','Pipeline'],['weightedPipeline','Pipeline ponderado'],['completedTasks','Trabalhos concluídos'],['delayedTasks','Trabalhos atrasados'],['onTimeRate','Entrega no prazo']];
export default function GoalsPage(){
  const bootstrap=useQuery({queryKey:['management-bootstrap'],queryFn:managementApi.bootstrap});const fields=[{name:'month',label:'Mês',type:'number' as const,required:true},{name:'year',label:'Ano',type:'number' as const,required:true},{name:'area',label:'Área',type:'select' as const,required:true,options:['empresa','marketing','comercial','operacional','financeiro'].map((value)=>({value,label:value}))},{name:'kpi',label:'KPI',type:'select' as const,required:true,options:kpis.map(([value,label])=>({value,label}))},{name:'targetValue',label:'Valor da meta',type:'number' as const,required:true},{name:'unit',label:'Unidade',type:'select' as const,required:true,options:[['kz','Kz'],['percentagem','Percentagem'],['quantidade','Quantidade'],['horas','Horas'],['dias','Dias']].map(([value,label])=>({value,label}))},{name:'responsibleUserId',label:'Responsável',type:'select' as const,options:(bootstrap.data?.profiles||[]).map((profile)=>({value:profile.id,label:profile.fullName}))},{name:'notes',label:'Observações',type:'textarea' as const}];
  const showValue=(value:string|number|null|undefined,unit:string)=>unit==='kz'?formatKz(value):unit==='percentagem'?formatPercent(Number(value||0)):String(Number(value||0));
  return <ManagementResourcePage<Goal> title="Metas" description="Metas mensais comparadas automaticamente com os KPIs realizados." queryKey="management-goals" load={()=>managementApi.goals()} create={managementApi.createGoal} update={managementApi.updateGoal} remove={managementApi.deleteGoal} createLabel="Nova meta" fields={fields} columns={[
    {label:'KPI',render:(row)=><div><p className="font-semibold">{kpis.find(([key])=>key===row.kpi)?.[1]||row.kpi}</p><p className="text-xs text-slate-500">{row.area} · {String(row.month).padStart(2,'0')}/{row.year}</p></div>,searchValue:(row)=>`${row.kpi} ${row.area}`},{label:'Meta',render:(row)=>showValue(row.targetValue,row.unit)},{label:'Realizado',render:(row)=>showValue(row.actualValue,row.unit)},{label:'Diferença',render:(row)=>showValue(Number(row.actualValue||0)-Number(row.targetValue||0),row.unit)},{label:'Cumprimento',render:(row)=>formatPercent(row.fulfillment||0)},{label:'Estado',render:(row)=><StatusBadge value={row.state||'vermelho'}/>},{label:'Responsável',render:(row)=>row.responsible?.fullName||'Empresa'}
  ]} toInitialValues={(row)=>({...row})} />;
}
