'use client';

import { useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { DragDropContext, Draggable, Droppable, type DropResult } from '@hello-pangea/dnd';
import { Plus } from 'lucide-react';
import { Button } from '@/components/ui/button';
import ManagementFormDialog from '@/components/management/management-form-dialog';
import { KpiCard, ManagementLoading, ManagementPage, StatusBadge } from '@/components/management/management-ui';
import { managementApi, type ManagementOpportunity } from '@/lib/management-api';
import { formatDate, formatKz, formatPercent } from '@/lib/management-format';
import { useToast } from '@/components/ui/toast-provider';

export default function CommercialPage() {
  const qc=useQueryClient(); const {toast}=useToast(); const [open,setOpen]=useState(false); const [editing,setEditing]=useState<ManagementOpportunity|null>(null);
  const opportunities=useQuery({queryKey:['management-opportunities'],queryFn:managementApi.opportunities}); const bootstrap=useQuery({queryKey:['management-bootstrap'],queryFn:managementApi.bootstrap});
  const save=useMutation({mutationFn:(values:Record<string,unknown>)=>editing?managementApi.updateOpportunity(editing.id,values):managementApi.createOpportunity(values),onSuccess:()=>{qc.invalidateQueries({queryKey:['management-opportunities']});setOpen(false);setEditing(null);toast({title:'Oportunidade guardada',variant:'success'});}});
  const move=useMutation({mutationFn:({id,stage}:{id:string;stage:string})=>managementApi.moveOpportunity(id,stage),onSuccess:()=>qc.invalidateQueries({queryKey:['management-opportunities']}),onError:()=>toast({title:'Não foi possível mover a oportunidade',variant:'error'})});
  const rows=opportunities.data||[]; const won=rows.filter((row)=>row.stage==='ganho').length; const lost=rows.filter((row)=>row.stage==='perdido').length; const openRows=rows.filter((row)=>!['ganho','perdido'].includes(row.stage));
  const profiles=(bootstrap.data?.profiles||[]).filter((profile)=>['admin','commercial'].includes(profile.role)).map((profile)=>({value:profile.id,label:profile.fullName}));
  const clients=useQuery({queryKey:['management-clients'],queryFn:()=>managementApi.clients()});
  const fields=[{name:'clientId',label:'Cliente existente',type:'select' as const,options:(clients.data||[]).map((client)=>({value:client.id,label:client.companyName}))},{name:'companyName',label:'Empresa',required:true},{name:'contactName',label:'Nome do contacto',required:true},{name:'phone',label:'Telefone'},{name:'email',label:'E-mail',type:'email' as const},{name:'leadSource',label:'Origem do lead'},{name:'responsibleUserId',label:'Responsável comercial',type:'select' as const,options:profiles},{name:'entryDate',label:'Data de entrada',type:'date' as const,required:true},{name:'firstContactDate',label:'Primeiro contacto',type:'datetime-local' as const},{name:'nextInteractionDate',label:'Próxima interação',type:'datetime-local' as const},{name:'estimatedValue',label:'Valor estimado (Kz)',type:'number' as const,required:true},{name:'closeProbability',label:'Probabilidade (%)',type:'number' as const},{name:'meetingDate',label:'Data da reunião',type:'datetime-local' as const},{name:'proposalDate',label:'Data da proposta',type:'datetime-local' as const},{name:'expectedCloseDate',label:'Fecho previsto',type:'date' as const},{name:'lossReason',label:'Motivo de perda'},{name:'notes',label:'Observações',type:'textarea' as const}];
  const byStage=useMemo(()=>Object.fromEntries((bootstrap.data?.stages||[]).map((stage)=>[stage.stage,rows.filter((row)=>row.stage===stage.stage)])),[bootstrap.data?.stages,rows]);
  const onDragEnd=(result:DropResult)=>{if(!result.destination)return;const id=result.draggableId;const stage=result.destination.droppableId;const current=rows.find((row)=>row.id===id);if(current&&current.stage!==stage)move.mutate({id,stage});};
  if(opportunities.isLoading||bootstrap.isLoading)return <ManagementLoading/>;
  return <ManagementPage title="Comercial" description="Pipeline, oportunidades e histórico de vendas." action={<Button onClick={()=>{setEditing(null);setOpen(true)}}><Plus className="mr-2 h-4 w-4"/>Nova oportunidade</Button>}>
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5"><KpiCard label="Total de leads" value={rows.length}/><KpiCard label="Ganhos" value={won} tone="green"/><KpiCard label="Perdidos" value={lost} tone="red"/><KpiCard label="Taxa de fecho" value={formatPercent(won+lost?won/(won+lost)*100:null)}/><KpiCard label="Pipeline ponderado" value={formatKz(openRows.reduce((sum,row)=>sum+Number(row.estimatedValue)*Number(row.closeProbability)/100,0))} tone="amber"/></div>
    <DragDropContext onDragEnd={onDragEnd}><div className="flex gap-4 overflow-x-auto pb-4">{(bootstrap.data?.stages||[]).map((stage)=><div className="w-72 flex-none" key={stage.id}><Droppable droppableId={stage.stage}>{(provided)=><section ref={provided.innerRef} {...provided.droppableProps} className="min-h-[420px] rounded-2xl bg-slate-100 p-3 dark:bg-slate-900"><div className="mb-3 flex items-center justify-between"><div><h2 className="text-sm font-bold">{stage.label}</h2><p className="text-xs text-slate-500">{Number(stage.probability)}%</p></div><span className="rounded-full bg-white px-2 py-1 text-xs font-bold dark:bg-slate-800">{byStage[stage.stage]?.length||0}</span></div>{(byStage[stage.stage]||[]).map((row,index)=><Draggable draggableId={row.id} index={index} key={row.id}>{(drag)=><button ref={drag.innerRef} {...drag.draggableProps} {...drag.dragHandleProps} onClick={()=>{setEditing(row);setOpen(true)}} className="mb-3 w-full rounded-xl border border-slate-200 bg-white p-3 text-left shadow-sm dark:border-slate-700 dark:bg-slate-800"><p className="font-semibold">{row.companyName}</p><p className="mt-1 text-xs text-slate-500">{row.contactName}</p><p className="mt-3 font-bold text-blue-600">{formatKz(row.estimatedValue)}</p><div className="mt-2 flex items-center justify-between"><StatusBadge value={row.stage}/><span className="text-[10px] text-slate-400">{formatDate(row.expectedCloseDate)}</span></div></button>}</Draggable>)}{provided.placeholder}</section>}</Droppable></div>)}</div></DragDropContext>
    <ManagementFormDialog open={open} onOpenChange={setOpen} title={editing?'Editar oportunidade':'Nova oportunidade'} fields={fields} initialValues={editing?{...editing,entryDate:editing.entryDate.slice(0,10),expectedCloseDate:editing.expectedCloseDate?.slice(0,10)||''}:{entryDate:new Date().toISOString().slice(0,10),estimatedValue:0,closeProbability:10}} isEditing={Boolean(editing)} submitting={save.isPending} onSubmit={(values)=>save.mutateAsync(values)}/>
  </ManagementPage>;
}
