'use client';

import Link from 'next/link';
import { FormEvent, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ArrowRight, Building2, Plus, Search, X } from 'lucide-react';
import { GrowthBadge, GrowthButton, GrowthCard, GrowthField, GrowthPage, growthInputClass, growthTextareaClass, EmptyGrowth } from '@/components/growth/growth-ui';
import { formatGrowthKz, growthApi } from '@/lib/growth-api';

const statusLabel = { active: 'Ativo', paused: 'Pausado', finished: 'Finalizado', archived: 'Arquivado' } as const;

export default function GrowthClientsPage() {
  const qc = useQueryClient(); const [search, setSearch] = useState(''); const [open, setOpen] = useState(false);
  const query = useQuery({ queryKey: ['growth-clients'], queryFn: growthApi.clients });
  const create = useMutation({ mutationFn: growthApi.createClient, onSuccess: ()=>{ qc.invalidateQueries({ queryKey:['growth-clients'] }); setOpen(false); } });
  const rows = (query.data || []).filter((client)=>client.companyName.toLowerCase().includes(search.toLowerCase()));
  return <GrowthPage eyebrow="Admin Mazanga" title="Clientes" description="Cada cliente tem uma sala independente para transformar dados em decisões de crescimento." action={<GrowthButton onClick={()=>setOpen(true)}><Plus className="h-4 w-4"/>Novo cliente</GrowthButton>}>
    <GrowthCard className="mb-5 p-3"><div className="relative max-w-md"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-white/30"/><input value={search} onChange={(e)=>setSearch(e.target.value)} className={`${growthInputClass} pl-10`} placeholder="Pesquisar empresa…"/></div></GrowthCard>
    {!query.isLoading && !rows.length ? <EmptyGrowth title="Ainda não há clientes" description="Cria o primeiro espaço e começa a preparar uma leitura estratégica."/> : <div className="grid gap-4 xl:grid-cols-2">{rows.map((client)=>{ const period=client.periods?.[0]; return <GrowthCard key={client.id} className="group p-0 transition hover:border-[#FF5D00]/25"><div className="flex items-start gap-4 p-5"><div className="grid h-12 w-12 shrink-0 place-items-center overflow-hidden rounded-xl bg-white/8 text-white/60">{client.logoUrl ? <img src={client.logoUrl} alt="" className="h-full w-full object-cover"/> : <Building2 className="h-5 w-5"/>}</div><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-3"><div><h2 className="truncate text-lg font-bold text-white">{client.companyName}</h2><p className="mt-1 text-xs text-white/35">{client.sector || 'Setor não definido'}</p></div><GrowthBadge tone={client.status==='active'?'lime':'neutral'}>{statusLabel[client.status]}</GrowthBadge></div><div className="mt-6 grid grid-cols-3 gap-3 border-t border-white/[.07] pt-5"><Stat label="Contactos" value={period?.contacts ?? '—'}/><Stat label="Receita" value={period ? formatGrowthKz(period.attributedRevenue) : '—'}/><Stat label="Atualização" value={new Date(client.updatedAt).toLocaleDateString('pt-PT')}/></div></div></div><Link href={`/clientes/${client.id}`} className="flex items-center justify-between border-t border-white/[.07] px-5 py-3 text-xs font-bold uppercase tracking-[.12em] text-[#FF5D00] hover:bg-white/[.025]">Abrir Growth Room<ArrowRight className="h-4 w-4 transition group-hover:translate-x-1"/></Link></GrowthCard>;})}</div>}
    {open && <div className="fixed inset-0 z-[90] grid place-items-center bg-black/75 p-4 backdrop-blur-sm"><ClientForm busy={create.isPending} error={create.error} onClose={()=>setOpen(false)} onSubmit={(data)=>create.mutate(data)}/></div>}
  </GrowthPage>;
}
function Stat({label,value}:{label:string;value:string|number}) { return <div><p className="text-[10px] font-bold uppercase tracking-[.1em] text-white/25">{label}</p><p className="mt-1 truncate text-sm font-semibold text-white/75">{value}</p></div>; }
function ClientForm({onClose,onSubmit,busy,error}:{onClose:()=>void;onSubmit:(data:Record<string,string>)=>void;busy:boolean;error:unknown}) {
  const [form,setForm]=useState({companyName:'',sector:'',contactName:'',contactEmail:'',phone:'',mainGoal:'',logoUrl:'',status:'active'});
  const set=(key:string,value:string)=>setForm((old)=>({...old,[key]:value}));
  const submit=(e:FormEvent)=>{e.preventDefault();onSubmit(form)};
  return <form onSubmit={submit} className="max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-3xl border border-white/10 bg-[#111111] p-6 shadow-2xl md:p-8"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#FF5D00]">Novo espaço</p><h2 className="mt-2 text-2xl font-bold text-white">Criar cliente</h2></div><button type="button" onClick={onClose} className="rounded-xl p-2 text-white/40 hover:bg-white/5 hover:text-white"><X className="h-5 w-5"/></button></div>{Boolean(error) && <p className="mt-4 rounded-xl bg-red-500/10 p-3 text-sm text-red-200">Não foi possível criar o cliente.</p>}<div className="mt-7 grid gap-5 md:grid-cols-2"><GrowthField label="Nome da empresa"><input required className={growthInputClass} value={form.companyName} onChange={(e)=>set('companyName',e.target.value)}/></GrowthField><GrowthField label="Setor"><input className={growthInputClass} value={form.sector} onChange={(e)=>set('sector',e.target.value)}/></GrowthField><GrowthField label="Pessoa de contacto"><input className={growthInputClass} value={form.contactName} onChange={(e)=>set('contactName',e.target.value)}/></GrowthField><GrowthField label="Email"><input type="email" className={growthInputClass} value={form.contactEmail} onChange={(e)=>set('contactEmail',e.target.value)}/></GrowthField><GrowthField label="Telefone"><input className={growthInputClass} value={form.phone} onChange={(e)=>set('phone',e.target.value)}/></GrowthField><GrowthField label="URL do logótipo"><input type="url" className={growthInputClass} value={form.logoUrl} onChange={(e)=>set('logoUrl',e.target.value)}/></GrowthField><div className="md:col-span-2"><GrowthField label="Objetivo principal"><textarea className={growthTextareaClass} value={form.mainGoal} onChange={(e)=>set('mainGoal',e.target.value)}/></GrowthField></div></div><div className="mt-7 flex justify-end gap-3"><GrowthButton type="button" variant="secondary" onClick={onClose}>Cancelar</GrowthButton><GrowthButton disabled={busy}>{busy?'A criar…':'Criar Growth Room'}</GrowthButton></div></form>;
}
