'use client';

import { useEffect, useState } from 'react';
import { useSearchParams } from 'next/navigation';
import { useQuery } from '@tanstack/react-query';
import { ArrowDown, ArrowUpRight, BarChart3, CalendarDays, CheckCircle2, CircleDollarSign, Lightbulb, Target, TrendingUp, Users } from 'lucide-react';
import { EmptyGrowth, GrowthBadge, GrowthCard, GrowthPage } from '@/components/growth/growth-ui';
import { formatGrowthKz, formatGrowthPercent, GrowthGoalEvaluation, GrowthSnapshot, growthApi } from '@/lib/growth-api';

const quality={low:'Baixa',medium:'Média',high:'Alta',very_high:'Muito alta'} as const;
const campaignStatus={testing:'Em teste',maintain:'A manter',scale:'A escalar',optimize:'A otimizar',pause:'A pausar',finished:'Finalizada'} as const;

export default function GrowthPortalPage(){
  const search=useSearchParams();const section=search.get('secao')||'overview';const previewClientId=search.get('clientId');const initialPeriodId=search.get('periodId')||'';const query=useQuery({queryKey:['growth-portal',previewClientId],queryFn:()=>growthApi.portal(previewClientId)});const [periodId,setPeriodId]=useState(initialPeriodId);
  useEffect(()=>{if(query.data?.periods.length&&!periodId)setPeriodId(query.data.periods[0].id)},[query.data,periodId]);
  if(query.isLoading)return <div className="p-10 text-white/40">A preparar a leitura…</div>;
  if(!query.data?.periods.length)return <GrowthPage eyebrow="A tua sala" title={query.data?.client.companyName||'Growth Room'} description="Os resultados publicados pela Mazanga aparecem aqui." action={null}><EmptyGrowth title="Ainda não há períodos publicados" description="A equipa Mazanga está a preparar a tua primeira leitura estratégica."/></GrowthPage>;
  const selectedIndex=Math.max(0,query.data.periods.findIndex((period)=>period.id===periodId));const selected=query.data.periods[selectedIndex]||query.data.periods[0];const snapshot=selected.publication.snapshot;const previousSnapshot=query.data.periods[selectedIndex+1]?.publication.snapshot;
  const titles:Record<string,[string,string]>={overview:['Visão geral','Os números mais importantes e o que significam para o negócio.'],origins:['Origem dos contactos','Que canais trouxeram volume, qualidade e receita.'],funnel:['Funil simples','Onde as oportunidades avançam e onde estamos a perder potencial.'],campaigns:['Campanhas e ações','O desempenho das iniciativas conduzidas neste período.'],reading:['Leitura estratégica','A interpretação consultiva da Mazanga sobre os resultados.'],decisions:['Próximas decisões','As ações prioritárias que transformam aprendizagem em crescimento.'],report:['Relatório de performance','Uma síntese executiva preparada para a reunião.']};const [title,description]=titles[section]||titles.overview;
  return <GrowthPage eyebrow={query.data.client.companyName} title={title} description={description} action={<label className="relative"><CalendarDays className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[#FF5D00]"/><select value={selected.id} onChange={(e)=>setPeriodId(e.target.value)} className="h-11 min-w-56 rounded-xl border border-white/10 bg-[#151b17] pl-10 pr-4 text-sm font-semibold text-white outline-none">{query.data.periods.map((period)=><option key={period.id} value={period.id}>{period.periodName}</option>)}</select></label>}>
    {section==='overview'&&<Overview snapshot={snapshot} previous={previousSnapshot}/>} {section==='origins'&&<Origins snapshot={snapshot}/>} {section==='funnel'&&<FunnelView snapshot={snapshot}/>} {section==='campaigns'&&<CampaignView snapshot={snapshot}/>} {section==='reading'&&<ReadingView snapshot={snapshot}/>} {section==='decisions'&&<DecisionView snapshot={snapshot}/>} {section==='report'&&<ReportView snapshot={snapshot}/>} 
    <p className="mt-8 text-right text-[10px] uppercase tracking-[.14em] text-white/20">Publicado em {new Date(selected.publication.publishedAt).toLocaleDateString('pt-PT')} · Versão {selected.publication.version}</p>
  </GrowthPage>;
}
const periodDelta=(current:unknown,previous:unknown)=>{const before=Number(previous||0);return before>0?(Number(current||0)-before)/before:null};
function Metric({label,value,detail,comparison,neutral=false,icon:Icon}:{label:string;value:string|number;detail?:string;comparison?:number|null;neutral?:boolean;icon:typeof Users}){const up=comparison!=null&&comparison>=0;return <GrowthCard className="relative overflow-hidden"><div className="absolute right-4 top-4 grid h-9 w-9 place-items-center rounded-xl bg-[#FF5D00]/10 text-[#FF5D00]"><Icon className="h-4 w-4"/></div><p className="pr-10 text-[10px] font-bold uppercase tracking-[.12em] text-white/30">{label}</p><p className="mt-5 text-2xl font-extrabold text-white">{value}</p>{detail&&<p className="mt-2 text-xs text-white/35">{detail}</p>}{comparison!=null&&<p className={`mt-2 text-xs font-bold ${neutral?'text-white/40':up?'text-[#FF5D00]':'text-amber-200'}`}>{up?'↑':'↓'} {formatGrowthPercent(Math.abs(comparison))} vs. período anterior</p>}</GrowthCard>}
function Overview({snapshot,previous}:{snapshot:GrowthSnapshot;previous?:GrowthSnapshot}){const p=snapshot.period,m=snapshot.metrics;const before=previous?.period;const beforeMetrics=previous?.metrics;return <>{previous&&<div className="mb-4 flex items-center gap-3 rounded-2xl border border-white/[.08] bg-white/[.035] px-5 py-4"><TrendingUp className="h-4 w-4 text-[#FF5D00]"/><p className="text-sm text-white/55">Comparação automática com <strong className="text-white/80">{previous.period.periodName}</strong></p></div>}<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Contactos recebidos" value={p.contacts} comparison={before?periodDelta(p.contacts,before.contacts):undefined} icon={Users}/><Metric label="Contactos qualificados" value={p.qualifiedContacts} detail={formatGrowthPercent(m.qualifiedRate)} comparison={before?periodDelta(p.qualifiedContacts,before.qualifiedContacts):undefined} icon={Target}/><Metric label="Reuniões marcadas" value={p.meetings} comparison={before?periodDelta(p.meetings,before.meetings):undefined} icon={CalendarDays}/><Metric label="Propostas enviadas" value={p.proposals} comparison={before?periodDelta(p.proposals,before.proposals):undefined} icon={TrendingUp}/><Metric label="Vendas fechadas" value={p.sales} comparison={before?periodDelta(p.sales,before.sales):undefined} icon={CheckCircle2}/><Metric label="Receita atribuída" value={formatGrowthKz(p.attributedRevenue)} comparison={before?periodDelta(p.attributedRevenue,before.attributedRevenue):undefined} icon={CircleDollarSign}/><Metric label="Investimento" value={formatGrowthKz(p.investment)} comparison={before?periodDelta(p.investment,before.investment):undefined} neutral icon={ArrowUpRight}/><Metric label="Retorno estimado" value={m.estimatedReturn==null?'Não disponível':`${m.estimatedReturn.toFixed(2)}x`} comparison={beforeMetrics?periodDelta(m.estimatedReturn,beforeMetrics.estimatedReturn):undefined} icon={BarChart3}/></div><GoalProgress items={snapshot.goals||[]}/><GrowthCard className="mt-5 border-[#FF5D00]/15 bg-[linear-gradient(135deg,rgba(255,93,0,.08),rgba(255,255,255,.03))] p-6 md:p-8"><p className="text-xs font-bold uppercase tracking-[.17em] text-[#FF5D00]">Resumo da Mazanga</p><p className="mt-5 max-w-4xl text-base leading-8 text-white/70 md:text-lg">{p.executiveSummary||'A leitura deste período será adicionada em breve.'}</p>{p.recommendation&&<div className="mt-6 border-l-2 border-[#FF5D00] pl-4"><p className="text-xs font-bold uppercase tracking-wider text-white/30">Decisão recomendada</p><p className="mt-2 text-sm leading-6 text-white/65">{p.recommendation}</p></div>}</GrowthCard></>}
function GoalProgress({items}:{items:GrowthGoalEvaluation[]}){if(!items.length)return null;const format=(value:number|null,unit:GrowthGoalEvaluation['unit'])=>value==null?'Não disponível':unit==='currency'?formatGrowthKz(value):unit==='multiple'?`${value.toFixed(2)}x`:new Intl.NumberFormat('pt-AO').format(value);const labels={achieved:'Atingida',at_risk:'Em risco',below:'Abaixo da meta',unavailable:'Sem dados'} as const;return <GrowthCard className="mt-5"><div className="flex items-center gap-2"><Target className="h-4 w-4 text-[#FF5D00]"/><p className="text-xs font-bold uppercase tracking-[.15em] text-white/45">Progresso das metas</p></div><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-5">{items.map((item)=><div key={item.key} className="rounded-2xl border border-white/[.07] bg-black/15 p-4"><div className="flex items-start justify-between gap-2"><p className="text-xs font-bold text-white/65">{item.label}</p><span className={`rounded-full px-2 py-1 text-[9px] font-bold uppercase ${item.status==='achieved'?'bg-[#FF5D00]/10 text-[#FF5D00]':item.status==='at_risk'?'bg-amber-300/10 text-amber-200':item.status==='below'?'bg-red-300/10 text-red-200':'bg-white/5 text-white/35'}`}>{labels[item.status]}</span></div><p className="mt-4 text-lg font-black text-white">{format(item.actual,item.unit)}</p><p className="mt-1 text-[10px] text-white/30">Meta: {format(item.target,item.unit)}</p><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-white/10"><div className={`h-full rounded-full ${item.status==='achieved'?'bg-[#FF5D00]':item.status==='at_risk'?'bg-amber-300':'bg-red-300'}`} style={{width:`${Math.min(100,Math.max(0,(item.progress||0)*100))}%`}}/></div></div>)}</div></GrowthCard>}
function Origins({snapshot}:{snapshot:GrowthSnapshot}){const rows=snapshot.period.sources||[];if(!rows.length)return <EmptyGrowth title="Sem detalhe por origem" description="Este período ainda não tem uma decomposição publicada por canal."/>;return <div className="space-y-3"><div className="hidden grid-cols-[1.2fr_repeat(5,.7fr)_1.8fr] gap-3 px-5 text-[10px] font-bold uppercase tracking-wider text-white/25 lg:grid"><span>Origem</span><span>Contactos</span><span>Qualificados</span><span>Reuniões</span><span>Vendas</span><span>Receita</span><span>Leitura</span></div>{rows.map((row)=><GrowthCard key={row.id||row.sourceName} className="grid gap-4 lg:grid-cols-[1.2fr_repeat(5,.7fr)_1.8fr] lg:items-center"><div><p className="font-bold text-white">{row.sourceName}</p><p className="mt-1 text-xs text-[#FF5D00]">Qualidade {quality[row.qualityLabel]}</p></div>{[['Contactos',row.contacts],['Qualificados',row.qualifiedContacts],['Reuniões',row.meetings],['Vendas',row.sales],['Receita',formatGrowthKz(row.revenue)]].map(([label,value])=><div key={String(label)}><p className="text-[10px] uppercase text-white/25 lg:hidden">{label}</p><p className="mt-1 text-sm font-semibold text-white/70">{value}</p></div>)}<p className="text-sm leading-6 text-white/50">{row.strategicReading||'Sem leitura adicional.'}</p></GrowthCard>)}</div>}
function FunnelView({snapshot}:{snapshot:GrowthSnapshot}){const p=snapshot.period;return <div className="space-y-5"><GrowthCard className="p-7"><div className="flex flex-col gap-3 lg:flex-row lg:items-stretch">{snapshot.metrics.funnel.map((stage,index)=><div key={stage.key} className="flex min-w-0 flex-1 items-center gap-3"><div className={`min-h-36 flex-1 rounded-2xl border p-5 ${snapshot.metrics.suggestedBottleneck===stage.key?'border-amber-300/30 bg-amber-300/[.07]':'border-white/[.07] bg-black/15'}`}><p className="text-[10px] font-bold uppercase leading-4 tracking-wider text-white/30">{stage.label}</p><p className="mt-4 text-3xl font-extrabold text-white">{stage.value}</p>{index>0&&<><p className="mt-2 text-xs text-[#FF5D00]">{formatGrowthPercent(stage.conversion)}</p><p className="mt-1 text-[10px] text-white/25">Queda de {stage.drop}</p></>}</div>{index<snapshot.metrics.funnel.length-1&&<ArrowDown className="h-4 w-4 shrink-0 text-white/20 lg:-rotate-90"/>}</div>)}</div></GrowthCard><GrowthCard className="border-amber-300/15"><p className="text-xs font-bold uppercase tracking-[.15em] text-amber-200">Maior gargalo comercial</p><p className="mt-4 max-w-4xl text-base leading-7 text-white/65">{p.mainBottleneck||p.strategicReading?.bottleneck||'A Mazanga não identificou um gargalo crítico neste período.'}</p></GrowthCard></div>}
function CampaignView({snapshot}:{snapshot:GrowthSnapshot}){const rows=snapshot.period.campaigns||[];if(!rows.length)return <EmptyGrowth title="Sem campanhas publicadas" description="As ações deste período ainda não foram detalhadas."/>;return <div className="grid gap-4 lg:grid-cols-2">{rows.map((row)=><GrowthCard key={row.id||row.name}><div className="flex items-start justify-between gap-4"><div><p className="text-lg font-bold text-white">{row.name}</p><p className="mt-1 text-xs text-white/30">{row.sourceName||'Canal não indicado'} · {row.objective||'Objetivo não indicado'}</p></div><GrowthBadge tone={row.status==='scale'||row.status==='maintain'?'lime':row.status==='pause'?'red':'amber'}>{campaignStatus[row.status]}</GrowthBadge></div><div className="mt-6 grid grid-cols-2 gap-4 border-y border-white/[.07] py-4 sm:grid-cols-4"><Small label="Investimento" value={formatGrowthKz(row.investment)}/><Small label="Contactos" value={row.contacts}/><Small label="Vendas" value={row.sales}/><Small label="Receita" value={formatGrowthKz(row.revenue)}/></div><div className="mt-5"><p className="text-[10px] font-bold uppercase tracking-wider text-[#FF5D00]">Decisão</p><p className="mt-2 text-sm leading-6 text-white/60">{row.decision||row.note||'Em análise.'}</p></div></GrowthCard>)}</div>}
function Small({label,value}:{label:string;value:string|number}){return <div><p className="text-[9px] font-bold uppercase tracking-wider text-white/25">{label}</p><p className="mt-2 text-sm font-bold text-white/75">{value}</p></div>}
function ReadingView({snapshot}:{snapshot:GrowthSnapshot}){const r=snapshot.period.strategicReading||{};const blocks=[['O que aconteceu',r.whatHappened],['O que os dados mostram',r.whatDataShows],['Onde está o gargalo',r.bottleneck],['O que isto significa para o negócio',r.businessMeaning],['Decisão recomendada',r.recommendedDecision],['Próximas ações da Mazanga',r.nextActions],['O que precisamos do cliente',r.clientNeeds]];return <div className="grid gap-4 lg:grid-cols-2">{blocks.map(([label,value],index)=><GrowthCard key={String(label)} className={index===3||index===4?'lg:col-span-2':''}><div className="flex gap-4"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-[#FF5D00]/10 text-[#FF5D00]"><Lightbulb className="h-4 w-4"/></div><div><p className="text-xs font-bold uppercase tracking-[.12em] text-white/30">{label}</p><p className="mt-3 text-sm leading-7 text-white/65">{value||'Sem informação adicional.'}</p></div></div></GrowthCard>)}</div>}
function DecisionView({snapshot}:{snapshot:GrowthSnapshot}){const rows=snapshot.period.decisions||[];if(!rows.length)return <EmptyGrowth title="Sem próximas decisões" description="As próximas ações serão publicadas pela Mazanga."/>;return <div className="space-y-4">{rows.map((row,index)=><GrowthCard key={row.id||index}><div className="flex flex-col gap-5 md:flex-row md:items-start"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-[#FF5D00] text-sm font-black text-[#FFFFFF]">{index+1}</span><div className="flex-1"><div className="flex flex-wrap items-center gap-3"><h2 className="text-lg font-bold text-white">{row.decision}</h2><GrowthBadge tone={row.priority==='high'?'amber':'neutral'}>Prioridade {row.priority==='high'?'alta':row.priority==='medium'?'média':'baixa'}</GrowthBadge></div><p className="mt-3 text-sm leading-6 text-white/50">{row.reason||'—'}</p><div className="mt-5 grid gap-4 border-t border-white/[.07] pt-4 sm:grid-cols-3"><Small label="Responsável" value={row.owner||'A definir'}/><Small label="Estado" value={row.status==='next_action'?'Próxima ação':row.status==='in_progress'?'Em curso':row.status==='completed'?'Concluída':'Cancelada'}/><Small label="Impacto esperado" value={row.expectedImpact||'—'}/></div></div></div></GrowthCard>)}</div>}
function ReportView({snapshot}:{snapshot:GrowthSnapshot}){const p=snapshot.period,r=p.report||{};const blocks=[['Resumo executivo',r.executiveSummary||p.executiveSummary],['Principais aprendizados',r.mainLearnings],['O que funcionou',r.whatWorked],['O que não funcionou',r.whatDidNotWork],['Decisões tomadas',r.decisionsTaken],['Próximos passos',r.nextSteps]];return <div className="rounded-3xl border border-white/10 bg-[#f2f5ed] p-6 text-[#152018] shadow-2xl md:p-10"><div className="border-b border-black/10 pb-7"><p className="text-xs font-black uppercase tracking-[.2em] text-[#47711e]">Mazanga Growth Room</p><div className="mt-4 flex flex-col justify-between gap-3 md:flex-row md:items-end"><div><h2 className="text-3xl font-black !text-[#152018]">Relatório de Performance</h2><p className="mt-2 text-sm text-black/45">{p.periodName} · {p.client?.companyName}</p></div><p className="text-sm font-bold text-black/45">{new Date(p.startDate).toLocaleDateString('pt-PT')} — {new Date(p.endDate).toLocaleDateString('pt-PT')}</p></div></div><div className="mt-8 grid gap-7 md:grid-cols-2">{blocks.map(([label,value],index)=><section key={String(label)} className={index===0?'md:col-span-2':''}><p className="text-[10px] font-black uppercase tracking-[.16em] text-[#47711e]">{label}</p><p className="mt-3 whitespace-pre-line text-sm leading-7 text-black/65">{value||'—'}</p></section>)}</div></div>}
